In [1]:
import torch

m=torch.rand(2,3)
n=torch.rand(2,3)

print(m)
print(n)


tensor([[0.3965, 0.5525, 0.9104],
        [0.0705, 0.2943, 0.6548]])
tensor([[0.0348, 0.5703, 0.8162],
        [0.4004, 0.4481, 0.4400]])


In [2]:
m+n

tensor([[0.4313, 1.1229, 1.7266],
        [0.4708, 0.7424, 1.0948]])

In [3]:
# Thhat is small but we work on big project then is change in

m.add_(n)
print(m)


tensor([[0.4313, 1.1229, 1.7266],
        [0.4708, 0.7424, 1.0948]])


In [4]:
print(n)

tensor([[0.0348, 0.5703, 0.8162],
        [0.4004, 0.4481, 0.4400]])


In [5]:
torch.relu(m)

tensor([[0.4313, 1.1229, 1.7266],
        [0.4708, 0.7424, 1.0948]])

In [6]:
m.relu_()

tensor([[0.4313, 1.1229, 1.7266],
        [0.4708, 0.7424, 1.0948]])

In [7]:
m.sigmoid_()

tensor([[0.6062, 0.7545, 0.8490],
        [0.6156, 0.6775, 0.7493]])

In [8]:
m.tanh_()

tensor([[0.5414, 0.6378, 0.6905],
        [0.5480, 0.5899, 0.6347]])

In [9]:
# Aap inplace operation ko use karein because ther is no need to create new memory its very fast

Cpying a tensor

In [10]:
A=torch.rand(2,3)
B=torch.rand(2,3)


print(A)
print(B)


tensor([[0.3980, 0.0804, 0.4488],
        [0.9306, 0.9123, 0.2169]])
tensor([[0.2693, 0.2687, 0.1231],
        [0.8654, 0.9840, 0.5901]])


In [11]:
A=B

In [12]:
A

tensor([[0.2693, 0.2687, 0.1231],
        [0.8654, 0.9840, 0.5901]])

In [13]:
A[0][0]=10
A

tensor([[10.0000,  0.2687,  0.1231],
        [ 0.8654,  0.9840,  0.5901]])

In [14]:
B

tensor([[10.0000,  0.2687,  0.1231],
        [ 0.8654,  0.9840,  0.5901]])

In [15]:
# That is not desireable 

In [16]:
id(B)


2028706308768

In [17]:
id(A)

2028706308768

In [18]:
A=B.clone()
A

tensor([[10.0000,  0.2687,  0.1231],
        [ 0.8654,  0.9840,  0.5901]])

In [19]:
A[1][1]=100
A

tensor([[ 10.0000,   0.2687,   0.1231],
        [  0.8654, 100.0000,   0.5901]])

In [20]:
B

tensor([[10.0000,  0.2687,  0.1231],
        [ 0.8654,  0.9840,  0.5901]])

In [21]:
id(A)

2028706678160

In [22]:
id(B)

2028706308768

Tensor on GPU 

In [23]:
if torch.cuda.is_available():
    print("GPU is available")
    device = "cuda"
    
else:
    device = "cpu"

print(device)

GPU is available
cuda


In [24]:
device=torch.device('cuda')


In [25]:
x=torch.rand(3,3)
x=x.to(device)
x

tensor([[0.2252, 0.7331, 0.4943],
        [0.3346, 0.8685, 0.8487],
        [0.8300, 0.6162, 0.5628]], device='cuda:0')

In [26]:
x+5

tensor([[5.2252, 5.7331, 5.4943],
        [5.3346, 5.8685, 5.8487],
        [5.8300, 5.6162, 5.5628]], device='cuda:0')

In [27]:
import time
#Define the size of the matrix
N=10000

#Create two random matrics

A=torch.randn(N,N)
B=torch.randn(N,N)

#Measure the time taken to perform matrix multiplication
start_time=time.time()
C=torch.mm(A,B)
end_time=time.time()

print(f"Time taken to perform matrix multiplication: {end_time-start_time} seconds")


Time taken to perform matrix multiplication: 2.178166151046753 seconds


In [28]:
C

tensor([[  85.6553,   17.5693, -114.1959,  ..., -111.6714,  -28.5966,
          -71.6181],
        [  79.9320,   26.6717,   19.3235,  ..., -120.0914,   54.1370,
          -38.1170],
        [ 100.0046,  -91.6877,  -25.9487,  ...,  -73.2044,   92.5110,
           99.3663],
        ...,
        [  65.4676,   68.7367,   81.3956,  ..., -103.5152, -117.1153,
          274.8927],
        [  47.9742,   -1.3852,  -23.8910,  ..., -101.3387,   35.7062,
           37.6353],
        [  31.1878,  -42.0753,  -55.4663,  ..., -186.8930,  -35.3568,
          -50.8281]])

In [29]:
# An now we give to the GPU
A=A.to(device)
B=B.to(device)

#Measure the time taken to perform matrix multiplication
start_time=time.time()
C=torch.mm(A,B)
end_time=time.time()

print(f"Time taken to perform matrix multiplication: {end_time-start_time} seconds")

Time taken to perform matrix multiplication: 0.0253298282623291 seconds


Reshaping the tensor

In [30]:
K=torch.rand(3,3)

In [31]:
L=torch.ones(4,4)
print(L)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [32]:
L.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [33]:
L.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])