In [1]:
import torch

m=torch.rand(2,3)
n=torch.rand(2,3)

print(m)
print(n)


tensor([[0.6349, 0.1441, 0.2312],
        [0.3402, 0.2047, 0.0806]])
tensor([[0.0326, 0.6077, 0.7814],
        [0.6368, 0.0518, 0.7972]])


In [2]:
m+n

tensor([[0.6675, 0.7518, 1.0126],
        [0.9770, 0.2566, 0.8778]])

In [3]:
# Thhat is small but we work on big project then is change in

m.add_(n)
print(m)


tensor([[0.6675, 0.7518, 1.0126],
        [0.9770, 0.2566, 0.8778]])


In [4]:
print(n)

tensor([[0.0326, 0.6077, 0.7814],
        [0.6368, 0.0518, 0.7972]])


In [5]:
torch.relu(m)

tensor([[0.6675, 0.7518, 1.0126],
        [0.9770, 0.2566, 0.8778]])

In [6]:
m.relu_()

tensor([[0.6675, 0.7518, 1.0126],
        [0.9770, 0.2566, 0.8778]])

In [7]:
m.sigmoid_()

tensor([[0.6609, 0.6796, 0.7335],
        [0.7265, 0.5638, 0.7064]])

In [8]:
m.tanh_()

tensor([[0.5790, 0.5912, 0.6252],
        [0.6209, 0.5108, 0.6084]])

In [9]:
# Aap inplace operation ko use karein because ther is no need to create new memory its very fast

Cpying a tensor

In [10]:
A=torch.rand(2,3)
B=torch.rand(2,3)


print(A)
print(B)


tensor([[0.3661, 0.6805, 0.4207],
        [0.5703, 0.0712, 0.9452]])
tensor([[0.1768, 0.2626, 0.3839],
        [0.1593, 0.2525, 0.6423]])


In [11]:
A=B

In [12]:
A

tensor([[0.1768, 0.2626, 0.3839],
        [0.1593, 0.2525, 0.6423]])

In [13]:
A[0][0]=10
A

tensor([[10.0000,  0.2626,  0.3839],
        [ 0.1593,  0.2525,  0.6423]])

In [14]:
B

tensor([[10.0000,  0.2626,  0.3839],
        [ 0.1593,  0.2525,  0.6423]])

In [15]:
# That is not desireable 

In [16]:
id(B)


2180827131200

In [17]:
id(A)

2180827131200

In [18]:
A=B.clone()
A

tensor([[10.0000,  0.2626,  0.3839],
        [ 0.1593,  0.2525,  0.6423]])

In [19]:
A[1][1]=100
A

tensor([[ 10.0000,   0.2626,   0.3839],
        [  0.1593, 100.0000,   0.6423]])

In [20]:
B

tensor([[10.0000,  0.2626,  0.3839],
        [ 0.1593,  0.2525,  0.6423]])

In [21]:
id(A)

2180827133760

In [22]:
id(B)

2180827131200

Tensor on GPU 

In [23]:
if torch.cuda.is_available():
    print("GPU is available")
    device = "cuda"
    
else:
    device = "cpu"

print(device)

GPU is available
cuda


In [24]:
device=torch.device('cuda')


In [25]:
x=torch.rand(3,3)
x=x.to(device)
x

tensor([[0.0495, 0.3093, 0.4895],
        [0.2875, 0.7820, 0.1484],
        [0.4981, 0.9941, 0.5012]], device='cuda:0')

In [26]:
x+5

tensor([[5.0495, 5.3094, 5.4895],
        [5.2875, 5.7820, 5.1484],
        [5.4981, 5.9941, 5.5012]], device='cuda:0')

In [27]:
import time
#Define the size of the matrix
N=10000

#Create two random matrics

A=torch.randn(N,N)
B=torch.randn(N,N)

#Measure the time taken to perform matrix multiplication
start_time=time.time()
C=torch.mm(A,B)
end_time=time.time()

print(f"Time taken to perform matrix multiplication: {end_time-start_time} seconds")


Time taken to perform matrix multiplication: 2.237299919128418 seconds


In [28]:
C

tensor([[-122.5106,  166.1505,   81.6667,  ..., -134.8629, -126.0051,
          185.5637],
        [ -32.2349,  188.0105,  -96.2330,  ..., -129.3192,  142.3066,
          249.9092],
        [ 141.9147,   60.8028, -110.5351,  ...,  -31.3398,    8.0568,
           91.7938],
        ...,
        [  31.1934,  158.6312,    5.1709,  ...,    5.8461,   40.6396,
          191.7314],
        [ -69.5720,  135.7299, -170.7188,  ...,   39.5754,   74.2484,
           80.7343],
        [ 102.9053,   94.7918,  -81.4477,  ...,    0.6674,  -17.0175,
           39.8702]])

In [29]:
# An now we give to the GPU
A=A.to(device)
B=B.to(device)

#Measure the time taken to perform matrix multiplication
start_time=time.time()
C=torch.mm(A,B)
end_time=time.time()

print(f"Time taken to perform matrix multiplication: {end_time-start_time} seconds")

Time taken to perform matrix multiplication: 0.1474010944366455 seconds


Reshaping the tensor

In [30]:
K=torch.rand(3,3)

In [31]:
L=torch.ones(4,4)
print(L)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [32]:
L.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [33]:
L.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])