In [22]:
import torch
print(torch.__version__)

2.5.1+cu118


Check the GPU in system

In [23]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("GPU is available")
    print(torch.cuda.get_device_name(0))
else:
    device = torch.device("cpu")
    print("GPU is not available")

# print(device)

GPU is available
NVIDIA GeForce RTX 4060 Laptop GPU


##### Using Pytorch make empty tensor

In [24]:
torch.empty(5,4)

tensor([[6.1175e+31, 8.1976e-43, 2.3694e-38, 2.3694e-38],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [25]:
a=torch.empty(5,4)
print(type(a))

<class 'torch.Tensor'>


In [26]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [27]:
torch.ones(5,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [28]:
torch.rand(4,4)

tensor([[0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696, 0.4414]])

In [29]:
torch.rand(4,4)
# there are same code the random value assign

tensor([[0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860, 0.5832],
        [0.3376, 0.8090, 0.5779, 0.9040]])

In [33]:
#manual_Seed

torch.manual_seed(22)

torch.rand(3,2)

tensor([[0.3659, 0.7025],
        [0.3104, 0.0097],
        [0.6577, 0.1947]])

In [35]:
torch.manual_seed(22)
torch.rand(3,2)

tensor([[0.3659, 0.7025],
        [0.3104, 0.0097],
        [0.6577, 0.1947]])

In [32]:
import torch

# same seed
torch.manual_seed(42)
print(torch.rand(3))

torch.manual_seed(42)
print(torch.rand(3))


tensor([0.8823, 0.9150, 0.3829])
tensor([0.8823, 0.9150, 0.3829])


In [36]:

torch.manual_seed(100)
print(torch.rand(3))

tensor([0.1117, 0.8158, 0.2626])
