In [45]:
import torch
print(torch.__version__)

if torch.cuda.is_available():
    print("CUDA is available")
    print("CUDA version:", torch.version.cuda)
    print("Number of GPUs:", torch.cuda.device_count())
    for i in range(torch.cuda.device_count()):
        print(f"GPU {i}: {torch.cuda.get_device_name(i)}")

2.5.1+cu118
CUDA is available
CUDA version: 11.8
Number of GPUs: 1
GPU 0: NVIDIA GeForce RTX 4060 Laptop GPU


### Tensor Shapes

In [46]:
x=torch.tensor([1,2,3])  #1D tensor
y=torch.tensor([[4,5,6],[7,8,9]]) #2D tensor
print(x.shape)
print(y.shape)


torch.Size([3])
torch.Size([2, 3])


In [47]:
k=torch.empty_like(y)
k

tensor([[0, 0, 0],
        [0, 0, 0]])

In [48]:
u=torch.empty_like(x)
u

tensor([0, 0, 0])

In [49]:
k=torch.ones_like(y)
k

tensor([[1, 1, 1],
        [1, 1, 1]])

In [50]:
k=torch.zeros_like(y)
k

tensor([[0, 0, 0],
        [0, 0, 0]])

In [51]:
a=torch.tensor([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(a.shape)
print(a)

b=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(b.shape)
print(b)



torch.Size([3, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])
torch.Size([2, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [52]:
y.dtype

torch.int64

In [63]:
k = torch.rand_like(y, dtype=torch.float32)
k

tensor([[0.3770, 0.7292, 0.3123],
        [0.6614, 0.3751, 0.3110]])

Check Dtype

In [54]:
L=torch.tensor([1.3, 34.2, 0,333])
L.dtype

torch.float32

In [57]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [56]:
K=torch.tensor([1.3, 34.2, 0,333],dtype=torch.int64)
K.type()

'torch.LongTensor'

In [61]:
z=torch.tensor([[4,8,7,5],[2,3,4,5]])
z

tensor([[4, 8, 7, 5],
        [2, 3, 4, 5]])

In [62]:
x.to(torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)