In [1]:
# Operation in tensor

import torch

# Create a tensor

x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

# Add the tensors

z = x + y
print(z)


tensor([5, 7, 9])


In [5]:
y=torch.rand(2,2)
print(y)
print(y+2)

tensor([[0.7889, 0.3787],
        [0.3166, 0.8087]])
tensor([[2.7889, 2.3787],
        [2.3166, 2.8087]])


In [6]:
y-2

tensor([[-1.2111, -1.6213],
        [-1.6834, -1.1913]])

In [7]:
y*3

tensor([[2.3666, 1.1360],
        [0.9497, 2.4262]])

Element-wise operations

In [12]:
import torch

a=torch.rand(3,4)
b=torch.rand(3,4)

print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Exponentiation:",a**b)


Addition: tensor([[0.2276, 0.6644, 1.6895, 1.0786],
        [1.4326, 1.3180, 0.9886, 1.0145],
        [0.9975, 0.7836, 0.5304, 0.3518]])
Subtraction: tensor([[ 0.1349, -0.2563,  0.1724, -0.4159],
        [-0.4453, -0.2108,  0.9451, -0.6830],
        [-0.2771, -0.5483, -0.3894, -0.2740]])
Multiplication: tensor([[0.0084, 0.0939, 0.7062, 0.2476],
        [0.4635, 0.4232, 0.0211, 0.1407],
        [0.2296, 0.0783, 0.0324, 0.0122]])
Division: tensor([[ 3.9106,  0.4433,  1.2273,  0.4435],
        [ 0.5257,  0.7242, 44.3621,  0.1953],
        [ 0.5652,  0.1767,  0.1533,  0.1243]])
Exponentiation: tensor([[0.9239, 0.4811, 0.9472, 0.4381],
        [0.5154, 0.6364, 0.9993, 0.2176],
        [0.5217, 0.2405, 0.2953, 0.3621]])


In [14]:
c=torch.tensor([-1,-2,3,-4])
torch.abs(c)

tensor([1, 2, 3, 4])

In [15]:
torch.neg(c)

tensor([ 1,  2, -3,  4])

In [25]:
# we use round 
d=torch.tensor([1.7,2.3,3.4,7.6])
print(torch.round(d))

tensor([2., 2., 3., 8.])


In [26]:
torch.ceil(d)

tensor([2., 3., 4., 8.])

In [27]:
#floor 
print(torch.floor(d))


tensor([1., 2., 3., 7.])


In [29]:
#clamp
torch.clamp(d,min=0,max=5)

tensor([1.7000, 2.3000, 3.4000, 5.0000])

Reduction operations