In [1]:
# Operation in tensor

import torch

# Create a tensor

x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

# Add the tensors

z = x + y
print(z)


tensor([5, 7, 9])


In [2]:
y=torch.rand(2,2)
print(y)
print(y+2)

tensor([[0.9286, 0.7533],
        [0.3778, 0.8408]])
tensor([[2.9286, 2.7533],
        [2.3778, 2.8408]])


In [3]:
y-2

tensor([[-1.0714, -1.2467],
        [-1.6222, -1.1592]])

In [4]:
y*3

tensor([[2.7857, 2.2598],
        [1.1335, 2.5224]])

Element-wise operations

In [5]:
import torch

a=torch.rand(3,4)
b=torch.rand(3,4)

print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Exponentiation:",a**b)


Addition: tensor([[0.6551, 1.9419, 0.8004, 0.9531],
        [0.5214, 1.1715, 1.2527, 0.6713],
        [1.6679, 0.5981, 0.7625, 0.8039]])
Subtraction: tensor([[ 0.0708, -0.0127, -0.1132, -0.1799],
        [-0.4140,  0.1284, -0.2950, -0.3100],
        [ 0.2393, -0.5596, -0.5135,  0.0573]])
Multiplication: tensor([[0.1060, 0.9427, 0.1570, 0.2190],
        [0.0251, 0.3390, 0.3706, 0.0886],
        [0.6812, 0.0112, 0.0794, 0.1607]])
Division: tensor([[1.2423, 0.9870, 0.7522, 0.6824],
        [0.1148, 1.2462, 0.6188, 0.3682],
        [1.3350, 0.0333, 0.1951, 1.1535]])
Exponentiation: tensor([[0.7437, 0.9654, 0.6139, 0.5837],
        [0.2547, 0.7988, 0.5656, 0.4319],
        [0.9666, 0.1016, 0.2647, 0.7301]])


In [6]:
c=torch.tensor([-1,-2,3,-4])
torch.abs(c)

tensor([1, 2, 3, 4])

In [7]:
torch.neg(c)

tensor([ 1,  2, -3,  4])

In [8]:
# we use round 
d=torch.tensor([1.7,2.3,3.4,7.6])
print(torch.round(d))

tensor([2., 2., 3., 8.])


In [9]:
torch.ceil(d)

tensor([2., 3., 4., 8.])

In [10]:
#floor 
print(torch.floor(d))


tensor([1., 2., 3., 7.])


In [11]:
#clamp
torch.clamp(d,min=0,max=5)

tensor([1.7000, 2.3000, 3.4000, 5.0000])

Reduction operations