### Mini Project: Linear Regression with Autograd

In [2]:
import torch
import torch.nn as nn

In [3]:
x=torch.tensor([[1.0],[2.0],[3.0],[4.0]]) 
y=torch.tensor([[5.0],[9.0],[6.0],[8.0]])

In [4]:
x

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [5]:
y

tensor([[5.],
        [9.],
        [6.],
        [8.]])

In [6]:
w= torch.randn(1, requires_grad=True)
b= torch.randn(1, requires_grad=True)
print(f"Initial weight: {w.item()}, Initial bias: {b.item()}")

Initial weight: 3.039306879043579, Initial bias: 0.054034050554037094


In [7]:
w

tensor([3.0393], requires_grad=True)

In [8]:
lr=0.01
epochs=1000

In [9]:
#Training loop

for epoch in range(epochs): 
    # Forward pass: predict y
    y_pred = x * w + b
    
    # Compute loss mse(mean squared error)
    loss = torch.mean((y_pred - y) ** 2)
    
    # Backward pass
    loss.backward()
    
    # Update weights
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad
        
        # Zero gradients after update
        w.grad.zero_()
        b.grad.zero_()
    # Print progress
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1}: w = {w.item():.4f}, b = {b.item():.4f}, loss = {loss.item():.6f}")

Epoch 10: w = 2.5413, b = 0.0700, loss = 7.152752
Epoch 20: w = 2.4154, b = 0.2071, loss = 6.767667
Epoch 30: w = 2.3508, b = 0.3597, loss = 6.490796
Epoch 40: w = 2.2973, b = 0.5109, loss = 6.232259
Epoch 50: w = 2.2469, b = 0.6582, loss = 5.988828
Epoch 60: w = 2.1982, b = 0.8012, loss = 5.759568
Epoch 70: w = 2.1510, b = 0.9400, loss = 5.543652
Epoch 80: w = 2.1051, b = 1.0747, loss = 5.340303
Epoch 90: w = 2.0607, b = 1.2054, loss = 5.148790
Epoch 100: w = 2.0175, b = 1.3323, loss = 4.968424
Epoch 110: w = 1.9757, b = 1.4554, loss = 4.798557
Epoch 120: w = 1.9350, b = 1.5749, loss = 4.638577
Epoch 130: w = 1.8956, b = 1.6908, loss = 4.487908
Epoch 140: w = 1.8573, b = 1.8033, loss = 4.346009
Epoch 150: w = 1.8202, b = 1.9125, loss = 4.212369
Epoch 160: w = 1.7841, b = 2.0185, loss = 4.086509
Epoch 170: w = 1.7492, b = 2.1213, loss = 3.967973
Epoch 180: w = 1.7152, b = 2.2211, loss = 3.856337
Epoch 190: w = 1.6823, b = 2.3180, loss = 3.751198
Epoch 200: w = 1.6503, b = 2.4120, loss 

In [10]:
print("\nFinal Model: y = {:.4f}x + {:.4f}".format(w.item(), b.item()))


Final Model: y = 0.6954x + 5.2195


In [11]:
s=torch.tensor([1,2,3,4,5],requires_grad=True)
s

RuntimeError: Only Tensors of floating point and complex dtype can require gradients