### Mini Project: Linear Regression with Autograd

In [1]:
import torch
import torch.nn as nn

In [2]:
x=torch.tensor([[1.0],[2.0],[3.0],[4.0]]) 
y=torch.tensor([[5.0],[9.0],[6.0],[8.0]])

In [3]:
x

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [4]:
y

tensor([[5.],
        [9.],
        [6.],
        [8.]])

In [5]:
w= torch.randn(1, requires_grad=True)
b= torch.randn(1, requires_grad=True)
print(f"Initial weight: {w.item()}, Initial bias: {b.item()}")

Initial weight: -0.45076873898506165, Initial bias: 0.32777124643325806


In [6]:
w

tensor([-0.4508], requires_grad=True)

In [7]:
lr=0.01
epochs=1000

In [8]:
#Training loop

for epoch in range(epochs): 
    # Forward pass: predict y
    y_pred = x * w + b
    
    # Compute loss mse(mean squared error)
    loss = torch.mean((y_pred - y) ** 2)
    
    # Backward pass
    loss.backward()
    
    # Update weights
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad
        
        # Zero gradients after update
        w.grad.zero_()
        b.grad.zero_()
    # Print progress
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1}: w = {w.item():.4f}, b = {b.item():.4f}, loss = {loss.item():.6f}")

Epoch 10: w = 1.6194, b = 1.1741, loss = 7.200577
Epoch 20: w = 1.9172, b = 1.4134, loss = 4.882549
Epoch 30: w = 1.9311, b = 1.5521, loss = 4.665463
Epoch 40: w = 1.9002, b = 1.6716, loss = 4.511879
Epoch 50: w = 1.8632, b = 1.7851, loss = 4.368550
Epoch 60: w = 1.8261, b = 1.8949, loss = 4.233597
Epoch 70: w = 1.7899, b = 2.0014, loss = 4.106501
Epoch 80: w = 1.7548, b = 2.1048, loss = 3.986801
Epoch 90: w = 1.7207, b = 2.2051, loss = 3.874069
Epoch 100: w = 1.6876, b = 2.3024, loss = 3.767900
Epoch 110: w = 1.6554, b = 2.3969, loss = 3.667909
Epoch 120: w = 1.6243, b = 2.4885, loss = 3.573738
Epoch 130: w = 1.5940, b = 2.5775, loss = 3.485048
Epoch 140: w = 1.5646, b = 2.6638, loss = 3.401522
Epoch 150: w = 1.5362, b = 2.7476, loss = 3.322856
Epoch 160: w = 1.5085, b = 2.8289, loss = 3.248769
Epoch 170: w = 1.4817, b = 2.9078, loss = 3.178994
Epoch 180: w = 1.4556, b = 2.9844, loss = 3.113281
Epoch 190: w = 1.4303, b = 3.0587, loss = 3.051392
Epoch 200: w = 1.4058, b = 3.1308, loss 

In [9]:
print("\nFinal Model: y = {:.4f}x + {:.4f}".format(w.item(), b.item()))


Final Model: y = 0.6732x + 5.2848
