### Mini Project: Linear Regression with Autograd

In [1]:
import torch
import torch.nn as nn

In [2]:
x=torch.tensor([[1.0],[2.0],[3.0],[4.0]]) 
y=torch.tensor([[5.0],[9.0],[6.0],[8.0]])

In [3]:
x

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [4]:
y

tensor([[5.],
        [9.],
        [6.],
        [8.]])

In [5]:
w= torch.randn(1, requires_grad=True)
b= torch.randn(1, requires_grad=True)
print(f"Initial weight: {w.item()}, Initial bias: {b.item()}")

Initial weight: -0.15965962409973145, Initial bias: -0.856700599193573


In [6]:
w

tensor([-0.1597], requires_grad=True)

In [7]:
lr=0.01
epochs=1000

In [8]:
#Training loop

for epoch in range(epochs): 
    # Forward pass: predict y
    y_pred = x * w + b
    
    # Compute loss mse(mean squared error)
    loss = torch.mean((y_pred - y) ** 2)
    
    # Backward pass
    loss.backward()
    
    # Update weights
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad
        
        # Zero gradients after update
        w.grad.zero_()
        b.grad.zero_()
    # Print progress
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1}: w = {w.item():.4f}, b = {b.item():.4f}, loss = {loss.item():.6f}")

Epoch 10: w = 1.9830, b = 0.0522, loss = 9.159947
Epoch 20: w = 2.2831, b = 0.3291, loss = 6.564144
Epoch 30: w = 2.2883, b = 0.5005, loss = 6.244944
Epoch 40: w = 2.2472, b = 0.6512, loss = 5.999316
Epoch 50: w = 2.2000, b = 0.7949, loss = 5.769408
Epoch 60: w = 2.1530, b = 0.9340, loss = 5.552917
Epoch 70: w = 2.1071, b = 1.0688, loss = 5.349029
Epoch 80: w = 2.0626, b = 1.1997, loss = 5.157009
Epoch 90: w = 2.0194, b = 1.3268, loss = 4.976165
Epoch 100: w = 1.9775, b = 1.4500, loss = 4.805847
Epoch 110: w = 1.9368, b = 1.5697, loss = 4.645442
Epoch 120: w = 1.8973, b = 1.6858, loss = 4.494374
Epoch 130: w = 1.8590, b = 1.7984, loss = 4.352099
Epoch 140: w = 1.8218, b = 1.9078, loss = 4.218105
Epoch 150: w = 1.7857, b = 2.0139, loss = 4.091910
Epoch 160: w = 1.7507, b = 2.1169, loss = 3.973060
Epoch 170: w = 1.7167, b = 2.2168, loss = 3.861128
Epoch 180: w = 1.6837, b = 2.3138, loss = 3.755711
Epoch 190: w = 1.6517, b = 2.4079, loss = 3.656430
Epoch 200: w = 1.6206, b = 2.4992, loss 

In [9]:
print("\nFinal Model: y = {:.4f}x + {:.4f}".format(w.item(), b.item()))


Final Model: y = 0.6927x + 5.2274


In [10]:
s=torch.tensor([1,2,3,4,5],requires_grad=True)


RuntimeError: Only Tensors of floating point and complex dtype can require gradients