### Mini Project: Linear Regression with Autograd

In [2]:
import torch
import torch.nn as nn

In [6]:
x=torch.tensor([[1.0],[2.0],[3.0],[4.0]]) 
y=torch.tensor([[5.0],[9.0],[6.0],[8.0]])

In [7]:
x

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [10]:
y

tensor([[5.],
        [9.],
        [6.],
        [8.]])

In [41]:
w= torch.randn(1, requires_grad=True)
b= torch.randn(1, requires_grad=True)
print(f"Initial weight: {w.item()}, Initial bias: {b.item()}")

Initial weight: -1.200311303138733, Initial bias: -0.17421944439411163


In [42]:
w

tensor([-1.2003], requires_grad=True)

In [54]:
lr=0.01
epochs=1000

In [55]:
#Training loop

for epoch in range(epochs): 
    # Forward pass: predict y
    y_pred = x * w + b
    
    # Compute loss mse(mean squared error)
    loss = torch.mean((y_pred - y) ** 2)
    
    # Backward pass
    loss.backward()
    
    # Update weights
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad
        
        # Zero gradients after update
        w.grad.zero_()
        b.grad.zero_()
    # Print progress
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1}: w = {w.item():.4f}, b = {b.item():.4f}, loss = {loss.item():.6f}")

Epoch 10: w = 0.8493, b = 4.7671, loss = 2.140249
Epoch 20: w = 0.8419, b = 4.7887, loss = 2.134996
Epoch 30: w = 0.8348, b = 4.8098, loss = 2.130049
Epoch 40: w = 0.8278, b = 4.8301, loss = 2.125390
Epoch 50: w = 0.8211, b = 4.8499, loss = 2.121002
Epoch 60: w = 0.8146, b = 4.8691, loss = 2.116869
Epoch 70: w = 0.8082, b = 4.8878, loss = 2.112977
Epoch 80: w = 0.8021, b = 4.9059, loss = 2.109311
Epoch 90: w = 0.7961, b = 4.9234, loss = 2.105859
Epoch 100: w = 0.7903, b = 4.9404, loss = 2.102608
Epoch 110: w = 0.7847, b = 4.9570, loss = 2.099546
Epoch 120: w = 0.7792, b = 4.9730, loss = 2.096662
Epoch 130: w = 0.7739, b = 4.9886, loss = 2.093946
Epoch 140: w = 0.7688, b = 5.0037, loss = 2.091388
Epoch 150: w = 0.7638, b = 5.0183, loss = 2.088979
Epoch 160: w = 0.7590, b = 5.0326, loss = 2.086710
Epoch 170: w = 0.7543, b = 5.0464, loss = 2.084574
Epoch 180: w = 0.7497, b = 5.0598, loss = 2.082561
Epoch 190: w = 0.7453, b = 5.0728, loss = 2.080666
Epoch 200: w = 0.7410, b = 5.0854, loss 

In [56]:
print("\nFinal Model: y = {:.4f}x + {:.4f}".format(w.item(), b.item()))


Final Model: y = 0.6128x + 5.4623
