### Mini Project: Linear Regression with Autograd

In [1]:
import torch
import torch.nn as nn

In [2]:
x=torch.tensor([[1.0],[2.0],[3.0],[4.0]]) 
y=torch.tensor([[5.0],[9.0],[6.0],[8.0]])

In [3]:
x

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [4]:
y

tensor([[5.],
        [9.],
        [6.],
        [8.]])

In [5]:
w= torch.randn(1, requires_grad=True)
b= torch.randn(1, requires_grad=True)
print(f"Initial weight: {w.item()}, Initial bias: {b.item()}")

Initial weight: 1.1427333354949951, Initial bias: 0.25232505798339844


In [6]:
w

tensor([1.1427], requires_grad=True)

In [7]:
lr=0.01
epochs=1000

In [8]:
#Training loop

for epoch in range(epochs): 
    # Forward pass: predict y
    y_pred = x * w + b
    
    # Compute loss mse(mean squared error)
    loss = torch.mean((y_pred - y) ** 2)
    
    # Backward pass
    loss.backward()
    
    # Update weights
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad
        
        # Zero gradients after update
        w.grad.zero_()
        b.grad.zero_()
    # Print progress
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1}: w = {w.item():.4f}, b = {b.item():.4f}, loss = {loss.item():.6f}")

Epoch 10: w = 2.0281, b = 0.7139, loss = 6.231939
Epoch 20: w = 2.1309, b = 0.9046, loss = 5.594164
Epoch 30: w = 2.1090, b = 1.0483, loss = 5.377671
Epoch 40: w = 2.0681, b = 1.1810, loss = 5.183720
Epoch 50: w = 2.0254, b = 1.3088, loss = 5.001314
Epoch 60: w = 1.9834, b = 1.4327, loss = 4.829532
Epoch 70: w = 1.9425, b = 1.5528, loss = 4.667749
Epoch 80: w = 1.9029, b = 1.6694, loss = 4.515382
Epoch 90: w = 1.8644, b = 1.7826, loss = 4.371884
Epoch 100: w = 1.8270, b = 1.8924, loss = 4.236739
Epoch 110: w = 1.7908, b = 1.9989, loss = 4.109459
Epoch 120: w = 1.7556, b = 2.1024, loss = 3.989588
Epoch 130: w = 1.7215, b = 2.2027, loss = 3.876694
Epoch 140: w = 1.6884, b = 2.3001, loss = 3.770371
Epoch 150: w = 1.6562, b = 2.3946, loss = 3.670237
Epoch 160: w = 1.6250, b = 2.4864, loss = 3.575930
Epoch 170: w = 1.5947, b = 2.5754, loss = 3.487114
Epoch 180: w = 1.5653, b = 2.6618, loss = 3.403466
Epoch 190: w = 1.5368, b = 2.7456, loss = 3.324687
Epoch 200: w = 1.5092, b = 2.8270, loss 

In [9]:
print("\nFinal Model: y = {:.4f}x + {:.4f}".format(w.item(), b.item()))


Final Model: y = 0.6826x + 5.2572
