In [56]:
import torch
print(torch.__version__)

print("Cuda",torch.cuda.is_available())


2.5.1+cu118
Cuda True


In [57]:
if torch.cuda.is_available():
    print("Cuda version",torch.version.cuda)
    print("using  device",torch.cuda.get_device_name())
else:
    print("Cuda not available, using CPU")

Cuda version 11.8
using  device NVIDIA GeForce RTX 4060 Laptop GPU


## Scaler_Operation

In [58]:
a=torch.rand(2, 3)
b=torch.rand(2, 3)

print("a:", a)
print("b:", b)

a: tensor([[0.6616, 0.7098, 0.2644],
        [0.9871, 0.1392, 0.4786]])
b: tensor([[0.7621, 0.5586, 0.6459],
        [0.8934, 0.1481, 0.7861]])


In [59]:
##addition
c = a + b
print("a + b:", c)

a + b: tensor([[1.4237, 1.2684, 0.9103],
        [1.8804, 0.2872, 1.2648]])


In [60]:
#Subtraction
a-b

tensor([[-0.1005,  0.1512, -0.3814],
        [ 0.0937, -0.0089, -0.3075]])

In [61]:
#Multiplication
d = a * b
print("a * b:", d)
#Division
e = a / b
print("a / b:", e)
#Matrix multiplication
f = torch.matmul(a, b.T)
print("a @ b.T:", f)

a * b: tensor([[0.5042, 0.3965, 0.1708],
        [0.8818, 0.0206, 0.3763]])
a / b: tensor([[0.8682, 1.2707, 0.4094],
        [1.1049, 0.9399, 0.6088]])
a @ b.T: tensor([[1.0715, 0.9041],
        [1.1391, 1.2787]])


In [62]:
x=torch.tensor([1,26,9,6,4,8,9])

In [63]:
torch.abs(x)  # Absolute values

tensor([ 1, 26,  9,  6,  4,  8,  9])

In [64]:
torch.neg(x)  # Negation

tensor([ -1, -26,  -9,  -6,  -4,  -8,  -9])

In [65]:
torch.exp(x)  # Exponential

tensor([2.7183e+00, 1.9573e+11, 8.1031e+03, 4.0343e+02, 5.4598e+01, 2.9810e+03,
        8.1031e+03])

In [66]:
torch.round(x)  # Rounding

tensor([ 1, 26,  9,  6,  4,  8,  9])

In [67]:
torch.clamp(x, min=5, max=10)  # Clamping values between 5 and 10

tensor([ 5, 10,  9,  6,  5,  8,  9])

In [68]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [69]:
torch.round(d)  # Rounding to nearest integer

tensor([2., 2., 4., 4.])

In [70]:
torch.floor(d)  # Rounding down to nearest integer

tensor([1., 2., 3., 4.])

In [71]:
torch.ceil(d)  # Ceiling maxmimum to nearest integer

tensor([2., 3., 4., 5.])

In [72]:
torch.clamp(d, min=5, max=10)  # Clamping values between 5 and 10

tensor([5., 5., 5., 5.])

## Reuction Operation

In [78]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [79]:
print(torch.sum(e)) # Sum of all elements
print(torch.sum(e, dim=0))  # Sum along the first dimension
  # Sum along the second dimension
print(torch.max(e))  # Maximum value in the tensor
print(torch.mean(e))  # Mean of all elements

tensor(30.)
tensor([12., 14.,  4.])
tensor(8.)
tensor(5.)


In [81]:
torch.median(e)  # Median of all elements
print("Standard Deviation",torch.std(e))  # Standard deviation of all elements
print(torch.var(e))  # Variance of all elements
print(torch.argmin(e))  # Index of the minimum value

Standard Deviation tensor(2.8284)
tensor(8.)
tensor(2)


In [82]:
# product
torch.prod(e)

tensor(4608.)

### Metrix Operation

In [92]:
m1=torch.randint(size=(3,4),low=0,high=10,dtype=torch.float32)
m2=torch.randint(size=(3,4),low=0,high=10,dtype=torch.float32)
print("Matrix 1:\n", m1)
print("Matrix 2:\n", m2)


Matrix 1:
 tensor([[6., 9., 6., 7.],
        [1., 1., 7., 2.],
        [4., 1., 6., 5.]])
Matrix 2:
 tensor([[3., 9., 4., 8.],
        [6., 5., 0., 6.],
        [4., 8., 2., 5.]])


In [93]:
## Matrix operations
print("Matrix addition:\n", m1 + m2)
print("Matrix subtraction:\n", m1 - m2)
print("Matrix multiplication:\n", m1 * m2)
print("Matrix division:\n", m1 / m2)
print("Matrix transpose:\n", m1.T)
print("Matrix dot product:\n", torch.matmul(m1, m2.T))

Matrix addition:
 tensor([[ 9., 18., 10., 15.],
        [ 7.,  6.,  7.,  8.],
        [ 8.,  9.,  8., 10.]])
Matrix subtraction:
 tensor([[ 3.,  0.,  2., -1.],
        [-5., -4.,  7., -4.],
        [ 0., -7.,  4.,  0.]])
Matrix multiplication:
 tensor([[18., 81., 24., 56.],
        [ 6.,  5.,  0., 12.],
        [16.,  8., 12., 25.]])
Matrix division:
 tensor([[2.0000, 1.0000, 1.5000, 0.8750],
        [0.1667, 0.2000,    inf, 0.3333],
        [1.0000, 0.1250, 3.0000, 1.0000]])
Matrix transpose:
 tensor([[6., 1., 4.],
        [9., 1., 1.],
        [6., 7., 6.],
        [7., 2., 5.]])
Matrix dot product:
 tensor([[179., 123., 143.],
        [ 56.,  23.,  36.],
        [ 85.,  59.,  61.]])


Element wise operation

In [95]:
a=torch.randint(size=(3,4),low=0,high=10,dtype=torch.float32)
b=torch.randint(size=(4,3),low=0,high=10,dtype=torch.float32)
print("Matrix A:\n", a)
print("Matrix B:\n", b)

# Matrix multiplication
c = torch.matmul(a, b)
print("Matrix multiplication result:\n", c)
# Element-wise operations
print("Element-wise addition:\n", a + b.T)
print("Element-wise subtraction:\n", a - b.T)

Matrix A:
 tensor([[3., 4., 8., 9.],
        [3., 7., 1., 2.],
        [5., 7., 2., 6.]])
Matrix B:
 tensor([[3., 7., 5.],
        [7., 5., 7.],
        [9., 8., 8.],
        [7., 7., 6.]])
Matrix multiplication result:
 tensor([[172., 168., 161.],
        [ 81.,  78.,  84.],
        [124., 128., 126.]])
Element-wise addition:
 tensor([[ 6., 11., 17., 16.],
        [10., 12.,  9.,  9.],
        [10., 14., 10., 12.]])
Element-wise subtraction:
 tensor([[ 0., -3., -1.,  2.],
        [-4.,  2., -7., -5.],
        [ 0.,  0., -6.,  0.]])


In [97]:
M1= torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
torch.det(M1)  # Determinant of a square matrix

tensor(94.)

## Comaprasion Methods

In [98]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

In [99]:
print("Tensor i:\n", i)
print("Tensor j:\n", j)


Tensor i:
 tensor([[9, 3, 8],
        [2, 8, 2]])
Tensor j:
 tensor([[2, 2, 5],
        [8, 6, 5]])


In [102]:
print(i>j)  # Element-wise comparison
print(i < j)  # Element-wise comparison
print(i == j)  # Element-wise equality check
print(i != j)  # Element-wise inequality check
print(i >= j)  # Element-wise greater than or equal to
print(i <= j)  # Element-wise less than or equal to
print(torch.all(i > j))  # Check if all elements in i are greater than j
print(torch.any(i < j))  # Check if any element in i is less than j
print(torch.logical_and(i > 5, j < 5))  # Element-wise logical AND
print(torch.logical_or(i < 5, j > 5))  # Element-wise logical OR

tensor([[ True,  True,  True],
        [False,  True, False]])
tensor([[False, False, False],
        [ True, False,  True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[ True,  True,  True],
        [False,  True, False]])
tensor([[False, False, False],
        [ True, False,  True]])
tensor(False)
tensor(True)
tensor([[ True, False, False],
        [False, False, False]])
tensor([[False,  True, False],
        [ True,  True,  True]])


6. Special Function

In [104]:
k=torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

print("Tensor k:\n", k)


Tensor k:
 tensor([[0., 5., 7.],
        [4., 1., 5.]])


In [105]:
#log

print(torch.log(k))  # Natural logarithm
print(torch.log10(k))  # Base-10 logarithm

tensor([[  -inf, 1.6094, 1.9459],
        [1.3863, 0.0000, 1.6094]])
tensor([[  -inf, 0.6990, 0.8451],
        [0.6021, 0.0000, 0.6990]])


In [106]:
#exp

print(torch.exp(k))  # Exponential function
print(torch.expm1(k))  # Exponential minus one

tensor([[1.0000e+00, 1.4841e+02, 1.0966e+03],
        [5.4598e+01, 2.7183e+00, 1.4841e+02]])
tensor([[   0.0000,  147.4132, 1095.6332],
        [  53.5981,    1.7183,  147.4132]])


In [109]:
print(torch.sqrt(k) ) # Square root
print(torch.rsqrt(k))  # Reciprocal square root

tensor([[0.0000, 2.2361, 2.6458],
        [2.0000, 1.0000, 2.2361]])
tensor([[   inf, 0.4472, 0.3780],
        [0.5000, 1.0000, 0.4472]])


In [110]:
#relu

print(torch.relu(k))  # Rectified Linear Unit (ReLU)

tensor([[0., 5., 7.],
        [4., 1., 5.]])


In [111]:
#softmax