In [1]:
import torch
print(torch.__version__)

print("Cuda",torch.cuda.is_available())


2.5.1+cu118
Cuda True


In [2]:
if torch.cuda.is_available():
    print("Cuda version",torch.version.cuda)
    print("using  device",torch.cuda.get_device_name())
else:
    print("Cuda not available, using CPU")

Cuda version 11.8
using  device NVIDIA GeForce RTX 4060 Laptop GPU


## Scaler_Operation

In [3]:
a=torch.rand(2, 3)
b=torch.rand(2, 3)

print("a:", a)
print("b:", b)

a: tensor([[0.0488, 0.1547, 0.5854],
        [0.9514, 0.4734, 0.9253]])
b: tensor([[0.0284, 0.3300, 0.1855],
        [0.2084, 0.3147, 0.5169]])


In [4]:
##addition
c = a + b
print("a + b:", c)

a + b: tensor([[0.0772, 0.4847, 0.7709],
        [1.1598, 0.7881, 1.4421]])


In [5]:
#Subtraction
a-b

tensor([[ 0.0204, -0.1753,  0.3999],
        [ 0.7430,  0.1586,  0.4084]])

In [6]:
#Multiplication
d = a * b
print("a * b:", d)
#Division
e = a / b
print("a / b:", e)
#Matrix multiplication
f = torch.matmul(a, b.T)
print("a @ b.T:", f)

a * b: tensor([[0.0014, 0.0510, 0.1086],
        [0.1983, 0.1490, 0.4782]])
a / b: tensor([[1.7205, 0.4689, 3.1564],
        [4.5653, 1.5040, 1.7901]])
a @ b.T: tensor([[0.1610, 0.3614],
        [0.3548, 0.8255]])


In [7]:
x=torch.tensor([1,26,9,6,4,8,9])

In [8]:
torch.abs(x)  # Absolute values

tensor([ 1, 26,  9,  6,  4,  8,  9])

In [9]:
torch.neg(x)  # Negation

tensor([ -1, -26,  -9,  -6,  -4,  -8,  -9])

In [10]:
torch.exp(x)  # Exponential

tensor([2.7183e+00, 1.9573e+11, 8.1031e+03, 4.0343e+02, 5.4598e+01, 2.9810e+03,
        8.1031e+03])

In [11]:
torch.round(x)  # Rounding

tensor([ 1, 26,  9,  6,  4,  8,  9])

In [12]:
torch.clamp(x, min=5, max=10)  # Clamping values between 5 and 10

tensor([ 5, 10,  9,  6,  5,  8,  9])

In [13]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [14]:
torch.round(d)  # Rounding to nearest integer

tensor([2., 2., 4., 4.])

In [15]:
torch.floor(d)  # Rounding down to nearest integer

tensor([1., 2., 3., 4.])

In [16]:
torch.ceil(d)  # Ceiling maxmimum to nearest integer

tensor([2., 3., 4., 5.])

In [17]:
torch.clamp(d, min=5, max=10)  # Clamping values between 5 and 10

tensor([5., 5., 5., 5.])

## Reuction Operation

In [18]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [19]:
print(torch.sum(e)) # Sum of all elements
print(torch.sum(e, dim=0))  # Sum along the first dimension
  # Sum along the second dimension
print(torch.max(e))  # Maximum value in the tensor
print(torch.mean(e))  # Mean of all elements

tensor(20.)
tensor([2., 9., 9.])
tensor(9.)
tensor(3.3333)


In [20]:
torch.median(e)  # Median of all elements
print("Standard Deviation",torch.std(e))  # Standard deviation of all elements
print(torch.var(e))  # Variance of all elements
print(torch.argmin(e))  # Index of the minimum value

Standard Deviation tensor(3.3862)
tensor(11.4667)
tensor(2)


In [21]:
# product
torch.prod(e)

tensor(0.)

### Metrix Operation

In [22]:
m1=torch.randint(size=(3,4),low=0,high=10,dtype=torch.float32)
m2=torch.randint(size=(3,4),low=0,high=10,dtype=torch.float32)
print("Matrix 1:\n", m1)
print("Matrix 2:\n", m2)


Matrix 1:
 tensor([[1., 1., 0., 8.],
        [5., 3., 0., 7.],
        [2., 8., 4., 5.]])
Matrix 2:
 tensor([[3., 3., 1., 5.],
        [9., 6., 1., 9.],
        [4., 8., 4., 0.]])


In [23]:
## Matrix operations
print("Matrix addition:\n", m1 + m2)
print("Matrix subtraction:\n", m1 - m2)
print("Matrix multiplication:\n", m1 * m2)
print("Matrix division:\n", m1 / m2)
print("Matrix transpose:\n", m1.T)
print("Matrix dot product:\n", torch.matmul(m1, m2.T))

Matrix addition:
 tensor([[ 4.,  4.,  1., 13.],
        [14.,  9.,  1., 16.],
        [ 6., 16.,  8.,  5.]])
Matrix subtraction:
 tensor([[-2., -2., -1.,  3.],
        [-4., -3., -1., -2.],
        [-2.,  0.,  0.,  5.]])
Matrix multiplication:
 tensor([[ 3.,  3.,  0., 40.],
        [45., 18.,  0., 63.],
        [ 8., 64., 16.,  0.]])
Matrix division:
 tensor([[0.3333, 0.3333, 0.0000, 1.6000],
        [0.5556, 0.5000, 0.0000, 0.7778],
        [0.5000, 1.0000, 1.0000,    inf]])
Matrix transpose:
 tensor([[1., 5., 2.],
        [1., 3., 8.],
        [0., 0., 4.],
        [8., 7., 5.]])
Matrix dot product:
 tensor([[ 46.,  87.,  12.],
        [ 59., 126.,  44.],
        [ 59., 115.,  88.]])


Element wise operation

In [24]:
a=torch.randint(size=(3,4),low=0,high=10,dtype=torch.float32)
b=torch.randint(size=(4,3),low=0,high=10,dtype=torch.float32)
print("Matrix A:\n", a)
print("Matrix B:\n", b)

# Matrix multiplication
c = torch.matmul(a, b)
print("Matrix multiplication result:\n", c)
# Element-wise operations
print("Element-wise addition:\n", a + b.T)
print("Element-wise subtraction:\n", a - b.T)

Matrix A:
 tensor([[8., 8., 8., 7.],
        [5., 1., 0., 4.],
        [4., 4., 1., 7.]])
Matrix B:
 tensor([[6., 6., 3.],
        [2., 4., 3.],
        [4., 6., 6.],
        [6., 2., 2.]])
Matrix multiplication result:
 tensor([[138., 142., 110.],
        [ 56.,  42.,  26.],
        [ 78.,  60.,  44.]])
Element-wise addition:
 tensor([[14., 10., 12., 13.],
        [11.,  5.,  6.,  6.],
        [ 7.,  7.,  7.,  9.]])
Element-wise subtraction:
 tensor([[ 2.,  6.,  4.,  1.],
        [-1., -3., -6.,  2.],
        [ 1.,  1., -5.,  5.]])


In [25]:
M1= torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
torch.det(M1)  # Determinant of a square matrix

tensor(-129.)

## Comaprasion Methods

In [26]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

In [27]:
print("Tensor i:\n", i)
print("Tensor j:\n", j)


Tensor i:
 tensor([[2, 5, 7],
        [6, 9, 9]])
Tensor j:
 tensor([[2, 8, 5],
        [9, 3, 9]])


In [28]:
print(i>j)  # Element-wise comparison
print(i < j)  # Element-wise comparison
print(i == j)  # Element-wise equality check
print(i != j)  # Element-wise inequality check
print(i >= j)  # Element-wise greater than or equal to
print(i <= j)  # Element-wise less than or equal to
print(torch.all(i > j))  # Check if all elements in i are greater than j
print(torch.any(i < j))  # Check if any element in i is less than j
print(torch.logical_and(i > 5, j < 5))  # Element-wise logical AND
print(torch.logical_or(i < 5, j > 5))  # Element-wise logical OR

tensor([[False, False,  True],
        [False,  True, False]])
tensor([[False,  True, False],
        [ True, False, False]])
tensor([[ True, False, False],
        [False, False,  True]])
tensor([[False,  True,  True],
        [ True,  True, False]])
tensor([[ True, False,  True],
        [False,  True,  True]])
tensor([[ True,  True, False],
        [ True, False,  True]])
tensor(False)
tensor(True)
tensor([[False, False, False],
        [False,  True, False]])
tensor([[ True,  True, False],
        [ True, False,  True]])


6. Special Function

In [29]:
k=torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

print("Tensor k:\n", k)


Tensor k:
 tensor([[1., 4., 8.],
        [2., 9., 0.]])


In [30]:
#log

print(torch.log(k))  # Natural logarithm
print(torch.log10(k))  # Base-10 logarithm

tensor([[0.0000, 1.3863, 2.0794],
        [0.6931, 2.1972,   -inf]])
tensor([[0.0000, 0.6021, 0.9031],
        [0.3010, 0.9542,   -inf]])


In [31]:
#exp

print(torch.exp(k))  # Exponential function
print(torch.expm1(k))  # Exponential minus one

tensor([[2.7183e+00, 5.4598e+01, 2.9810e+03],
        [7.3891e+00, 8.1031e+03, 1.0000e+00]])
tensor([[1.7183e+00, 5.3598e+01, 2.9800e+03],
        [6.3891e+00, 8.1021e+03, 0.0000e+00]])


In [32]:
print(torch.sqrt(k) ) # Square root
print(torch.rsqrt(k))  # Reciprocal square root

tensor([[1.0000, 2.0000, 2.8284],
        [1.4142, 3.0000, 0.0000]])
tensor([[1.0000, 0.5000, 0.3536],
        [0.7071, 0.3333,    inf]])


In [33]:
#relu

print(torch.relu(k))  # Rectified Linear Unit (ReLU)

tensor([[1., 4., 8.],
        [2., 9., 0.]])


In [34]:
#softmax