In [1]:
import torch
print(torch.__version__)

print("Cuda",torch.cuda.is_available())


2.5.1+cu118
Cuda True


In [2]:
if torch.cuda.is_available():
    print("Cuda version",torch.version.cuda)
    print("using  device",torch.cuda.get_device_name())
else:
    print("Cuda not available, using CPU")

Cuda version 11.8
using  device NVIDIA GeForce RTX 4060 Laptop GPU


## Scaler_Operation

In [3]:
a=torch.rand(2, 3)
b=torch.rand(2, 3)

print("a:", a)
print("b:", b)

a: tensor([[0.6294, 0.2174, 0.1480],
        [0.9994, 0.8314, 0.1658]])
b: tensor([[0.3763, 0.9914, 0.7014],
        [0.5263, 0.7209, 0.2824]])


In [4]:
##addition
c = a + b
print("a + b:", c)

a + b: tensor([[1.0056, 1.2089, 0.8494],
        [1.5257, 1.5523, 0.4481]])


In [5]:
#Subtraction
a-b

tensor([[ 0.2531, -0.7740, -0.5535],
        [ 0.4731,  0.1105, -0.1166]])

In [6]:
#Multiplication
d = a * b
print("a * b:", d)
#Division
e = a / b
print("a / b:", e)
#Matrix multiplication
f = torch.matmul(a, b.T)
print("a @ b.T:", f)

a * b: tensor([[0.2368, 0.2156, 0.1038],
        [0.5260, 0.5994, 0.0468]])
a / b: tensor([[1.6726, 0.2193, 0.2110],
        [1.8990, 1.1533, 0.5871]])
a @ b.T: tensor([[0.5562, 0.5298],
        [1.3166, 1.1722]])


In [7]:
x=torch.tensor([1,26,9,6,4,8,9])

In [8]:
torch.abs(x)  # Absolute values

tensor([ 1, 26,  9,  6,  4,  8,  9])

In [9]:
torch.neg(x)  # Negation

tensor([ -1, -26,  -9,  -6,  -4,  -8,  -9])

In [10]:
torch.exp(x)  # Exponential

tensor([2.7183e+00, 1.9573e+11, 8.1031e+03, 4.0343e+02, 5.4598e+01, 2.9810e+03,
        8.1031e+03])

In [11]:
torch.round(x)  # Rounding

tensor([ 1, 26,  9,  6,  4,  8,  9])

In [12]:
torch.clamp(x, min=5, max=10)  # Clamping values between 5 and 10

tensor([ 5, 10,  9,  6,  5,  8,  9])

In [13]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [14]:
torch.round(d)  # Rounding to nearest integer

tensor([2., 2., 4., 4.])

In [15]:
torch.floor(d)  # Rounding down to nearest integer

tensor([1., 2., 3., 4.])

In [16]:
torch.ceil(d)  # Ceiling maxmimum to nearest integer

tensor([2., 3., 4., 5.])

In [17]:
torch.clamp(d, min=5, max=10)  # Clamping values between 5 and 10

tensor([5., 5., 5., 5.])

## Reuction Operation

In [18]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [19]:
print(torch.sum(e)) # Sum of all elements
print(torch.sum(e, dim=0))  # Sum along the first dimension
  # Sum along the second dimension
print(torch.max(e))  # Maximum value in the tensor
print(torch.mean(e))  # Mean of all elements

tensor(29.)
tensor([11.,  4., 14.])
tensor(9.)
tensor(4.8333)


In [20]:
torch.median(e)  # Median of all elements
print("Standard Deviation",torch.std(e))  # Standard deviation of all elements
print(torch.var(e))  # Variance of all elements
print(torch.argmin(e))  # Index of the minimum value

Standard Deviation tensor(3.4303)
tensor(11.7667)
tensor(1)


In [21]:
# product
torch.prod(e)

tensor(0.)

### Metrix Operation

In [22]:
m1=torch.randint(size=(3,4),low=0,high=10,dtype=torch.float32)
m2=torch.randint(size=(3,4),low=0,high=10,dtype=torch.float32)
print("Matrix 1:\n", m1)
print("Matrix 2:\n", m2)


Matrix 1:
 tensor([[6., 1., 2., 7.],
        [9., 1., 3., 1.],
        [1., 1., 6., 4.]])
Matrix 2:
 tensor([[0., 1., 6., 0.],
        [7., 5., 6., 0.],
        [4., 9., 0., 8.]])


In [23]:
## Matrix operations
print("Matrix addition:\n", m1 + m2)
print("Matrix subtraction:\n", m1 - m2)
print("Matrix multiplication:\n", m1 * m2)
print("Matrix division:\n", m1 / m2)
print("Matrix transpose:\n", m1.T)
print("Matrix dot product:\n", torch.matmul(m1, m2.T))

Matrix addition:
 tensor([[ 6.,  2.,  8.,  7.],
        [16.,  6.,  9.,  1.],
        [ 5., 10.,  6., 12.]])
Matrix subtraction:
 tensor([[ 6.,  0., -4.,  7.],
        [ 2., -4., -3.,  1.],
        [-3., -8.,  6., -4.]])
Matrix multiplication:
 tensor([[ 0.,  1., 12.,  0.],
        [63.,  5., 18.,  0.],
        [ 4.,  9.,  0., 32.]])
Matrix division:
 tensor([[   inf, 1.0000, 0.3333,    inf],
        [1.2857, 0.2000, 0.5000,    inf],
        [0.2500, 0.1111,    inf, 0.5000]])
Matrix transpose:
 tensor([[6., 9., 1.],
        [1., 1., 1.],
        [2., 3., 6.],
        [7., 1., 4.]])
Matrix dot product:
 tensor([[13., 59., 89.],
        [19., 86., 53.],
        [37., 48., 45.]])


Element wise operation

In [24]:
a=torch.randint(size=(3,4),low=0,high=10,dtype=torch.float32)
b=torch.randint(size=(4,3),low=0,high=10,dtype=torch.float32)
print("Matrix A:\n", a)
print("Matrix B:\n", b)

# Matrix multiplication
c = torch.matmul(a, b)
print("Matrix multiplication result:\n", c)
# Element-wise operations
print("Element-wise addition:\n", a + b.T)
print("Element-wise subtraction:\n", a - b.T)

Matrix A:
 tensor([[7., 5., 8., 4.],
        [5., 3., 4., 4.],
        [7., 2., 8., 6.]])
Matrix B:
 tensor([[2., 5., 2.],
        [9., 8., 4.],
        [0., 2., 1.],
        [5., 4., 5.]])
Matrix multiplication result:
 tensor([[ 79., 107.,  62.],
        [ 57.,  73.,  46.],
        [ 62.,  91.,  60.]])
Element-wise addition:
 tensor([[ 9., 14.,  8.,  9.],
        [10., 11.,  6.,  8.],
        [ 9.,  6.,  9., 11.]])
Element-wise subtraction:
 tensor([[ 5., -4.,  8., -1.],
        [ 0., -5.,  2.,  0.],
        [ 5., -2.,  7.,  1.]])


In [25]:
M1= torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
torch.det(M1)  # Determinant of a square matrix

tensor(258.)

## Comaprasion Methods

In [26]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

In [27]:
print("Tensor i:\n", i)
print("Tensor j:\n", j)


Tensor i:
 tensor([[9, 2, 8],
        [7, 8, 5]])
Tensor j:
 tensor([[5, 2, 7],
        [4, 5, 7]])


In [28]:
print(i>j)  # Element-wise comparison
print(i < j)  # Element-wise comparison
print(i == j)  # Element-wise equality check
print(i != j)  # Element-wise inequality check
print(i >= j)  # Element-wise greater than or equal to
print(i <= j)  # Element-wise less than or equal to
print(torch.all(i > j))  # Check if all elements in i are greater than j
print(torch.any(i < j))  # Check if any element in i is less than j
print(torch.logical_and(i > 5, j < 5))  # Element-wise logical AND
print(torch.logical_or(i < 5, j > 5))  # Element-wise logical OR

tensor([[ True, False,  True],
        [ True,  True, False]])
tensor([[False, False, False],
        [False, False,  True]])
tensor([[False,  True, False],
        [False, False, False]])
tensor([[ True, False,  True],
        [ True,  True,  True]])
tensor([[ True,  True,  True],
        [ True,  True, False]])
tensor([[False,  True, False],
        [False, False,  True]])
tensor(False)
tensor(True)
tensor([[False, False, False],
        [ True, False, False]])
tensor([[False,  True,  True],
        [False, False,  True]])


6. Special Function

In [29]:
k=torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

print("Tensor k:\n", k)


Tensor k:
 tensor([[5., 8., 6.],
        [6., 1., 9.]])


In [30]:
#log

print(torch.log(k))  # Natural logarithm
print(torch.log10(k))  # Base-10 logarithm

tensor([[1.6094, 2.0794, 1.7918],
        [1.7918, 0.0000, 2.1972]])
tensor([[0.6990, 0.9031, 0.7782],
        [0.7782, 0.0000, 0.9542]])


In [31]:
#exp

print(torch.exp(k))  # Exponential function
print(torch.expm1(k))  # Exponential minus one

tensor([[1.4841e+02, 2.9810e+03, 4.0343e+02],
        [4.0343e+02, 2.7183e+00, 8.1031e+03]])
tensor([[1.4741e+02, 2.9800e+03, 4.0243e+02],
        [4.0243e+02, 1.7183e+00, 8.1021e+03]])


In [32]:
print(torch.sqrt(k) ) # Square root
print(torch.rsqrt(k))  # Reciprocal square root

tensor([[2.2361, 2.8284, 2.4495],
        [2.4495, 1.0000, 3.0000]])
tensor([[0.4472, 0.3536, 0.4082],
        [0.4082, 1.0000, 0.3333]])


In [33]:
#relu

print(torch.relu(k))  # Rectified Linear Unit (ReLU)

tensor([[5., 8., 6.],
        [6., 1., 9.]])


In [34]:
#softmax