In [1]:
import torch

In [2]:
print(torch.__version__)

2.5.1+cu118


In [3]:
print("GPU Avialabilty",torch.cuda.is_available())
print("GPU Device Count",torch.cuda.device_count())
print("GPU Device Name",torch.cuda.get_device_name(0))

GPU Avialabilty True
GPU Device Count 1
GPU Device Name NVIDIA GeForce RTX 4060 Laptop GPU


Cretaing Tesors and Metods

In [4]:
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
a=torch.empty(4,5)
print("Types",type(a))

Types <class 'torch.Tensor'>


In [6]:
#using zeros
torch.zeros(2,6)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [7]:
#using Ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.rand(3,6)

tensor([[0.9650, 0.9482, 0.2345, 0.1672, 0.3770, 0.5499],
        [0.9649, 0.4303, 0.8685, 0.3188, 0.9377, 0.7377],
        [0.0040, 0.7689, 0.8054, 0.3132, 0.9295, 0.5239]])

In [9]:
torch.rand(3,6)

tensor([[0.6307, 0.9214, 0.2244, 0.1911, 0.3277, 0.2319],
        [0.1310, 0.3326, 0.7585, 0.1837, 0.4478, 0.6101],
        [0.6473, 0.5673, 0.5355, 0.8381, 0.7659, 0.9315]])

In [10]:
#using seed
torch.manual_seed(42)
torch.rand(5,6)

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062]])

In [11]:
torch.manual_seed(42)
torch.rand(5,6)

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062]])

In [12]:
torch.tensor([[1,2,3,4],[4,5,6,9]])

tensor([[1, 2, 3, 4],
        [4, 5, 6, 9]])

In [13]:
#Other Ways

print("Arrange:-",torch.arange(0,10000,1000))

Arrange:- tensor([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000])


In [14]:
print("Linespace",torch.linspace(0,100,10))

Linespace tensor([  0.0000,  11.1111,  22.2222,  33.3333,  44.4444,  55.5556,  66.6667,
         77.7778,  88.8889, 100.0000])


In [15]:
print("Eye(Identity)",torch.eye(5))

Eye(Identity) tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [16]:
print("Using Full",torch.full((10,7),5))

Using Full tensor([[5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5]])
