In [1]:
import torch

In [3]:
print(torch.__version__)

2.6.0+cu124


In [4]:
print("GPU Avialabilty",torch.cuda.is_available())
print("GPU Device Count",torch.cuda.device_count())
print("GPU Device Name",torch.cuda.get_device_name(0))

GPU Avialabilty True
GPU Device Count 1
GPU Device Name Tesla T4


Cretaing Tesors and Metods

In [7]:
torch.empty(2,3)

tensor([[2.8183e+20, 6.1972e-04, 1.4588e-19],
        [7.2708e+31, 7.1430e+31, 1.5766e-19]])

In [8]:
a=torch.empty(4,5)
print("Types",type(a))

Types <class 'torch.Tensor'>


In [10]:
#using zeros
torch.zeros(2,6)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [11]:
#using Ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
torch.rand(3,6)

tensor([[0.0595, 0.8053, 0.3800, 0.7995, 0.5950, 0.5324],
        [0.3235, 0.5354, 0.0612, 0.5778, 0.1587, 0.9545],
        [0.3191, 0.7166, 0.3933, 0.7861, 0.9787, 0.5011]])

In [15]:
torch.rand(3,6)

tensor([[0.5858, 0.7911, 0.5986, 0.3322, 0.3564, 0.2020],
        [0.2942, 0.2891, 0.2449, 0.4904, 0.4813, 0.1547],
        [0.6387, 0.6663, 0.0782, 0.1822, 0.3371, 0.6073]])

In [16]:
#using seed
torch.manual_seed(42)
torch.rand(5,6)

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062]])

In [18]:
torch.manual_seed(42)
torch.rand(5,6)

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062]])

In [21]:
torch.tensor([[1,2,3,4],[4,5,6,9]])

tensor([[1, 2, 3, 4],
        [4, 5, 6, 9]])

In [27]:
#Other Ways

print("Arrange:-",torch.arange(0,10000,1000))

Arrange:- tensor([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000])


In [28]:
print("Linespace",torch.linspace(0,100,10))

Linespace tensor([  0.0000,  11.1111,  22.2222,  33.3333,  44.4444,  55.5556,  66.6667,
         77.7778,  88.8889, 100.0000])


In [29]:
print("Eye(Identity)",torch.eye(5))

Eye(Identity) tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [31]:
print("Using Full",torch.full((10,7),5))

Using Full tensor([[5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5]])
