In [19]:
import torch
import torch.nn as nn

In [38]:
class Model(nn.Module):
    def __init__(self,num_features):

        super().__init__()
        self.linear1= nn.Linear(num_features,1)
        self.sigmoid= nn.Sigmoid()

    def forward(self,features):
        out=self.linear1(features)
        out=self.sigmoid(out)

        return out

In [39]:
#Crete a datasets
x=torch.rand(10, 5)
#Create a model
# Model(fetures.shape[1])

# #Forward pass
# Model(features)
fetures.shape[1]


5

In [40]:
model = Model(x.shape[1])
# Forward pass
model(x)

tensor([[0.5047],
        [0.4672],
        [0.5054],
        [0.4779],
        [0.5089],
        [0.5721],
        [0.5502],
        [0.4663],
        [0.5282],
        [0.4646]], grad_fn=<SigmoidBackward0>)

In [44]:
model.linear1.weight
# model.linear1.weight.shapes

Parameter containing:
tensor([[-0.0289, -0.4377, -0.0256,  0.2285, -0.1791]], requires_grad=True)

In [45]:
model.linear1.bias

Parameter containing:
tensor([0.1872], requires_grad=True)

In [ ]:
# %pip install torchinfo    

In [48]:
from torchinfo import summary
# Model summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00