In [25]:
import torch
import torch.nn as nn



In [26]:
class Model(nn.Module):
    def __init__(self,num_features):

        super().__init__()
        self.layer_1 = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out=self.layer_1(features)
        out=self.sigmoid(out)
        return out
    

In [27]:
features=torch.rand(1000,12)
features.shape

torch.Size([1000, 12])

In [28]:
features

tensor([[0.3699, 0.1993, 0.7030,  ..., 0.8739, 0.4457, 0.2861],
        [0.5753, 0.5299, 0.0901,  ..., 0.0124, 0.3759, 0.0702],
        [0.8890, 0.2547, 0.2221,  ..., 0.0164, 0.9645, 0.3301],
        ...,
        [0.9134, 0.5837, 0.0042,  ..., 0.3588, 0.0379, 0.8291],
        [0.0585, 0.8924, 0.2491,  ..., 0.6989, 0.6882, 0.5101],
        [0.4562, 0.8126, 0.3895,  ..., 0.9921, 0.6832, 0.5859]])

In [29]:
num_features=features.shape[1]

In [30]:
model=Model(num_features)
model(features)

tensor([[0.5538],
        [0.5042],
        [0.5174],
        [0.6448],
        [0.5876],
        [0.6447],
        [0.5485],
        [0.5547],
        [0.5088],
        [0.5376],
        [0.5462],
        [0.5287],
        [0.5970],
        [0.5775],
        [0.5724],
        [0.5286],
        [0.5104],
        [0.5053],
        [0.5850],
        [0.5620],
        [0.5687],
        [0.5502],
        [0.5663],
        [0.5940],
        [0.5767],
        [0.5799],
        [0.5818],
        [0.5784],
        [0.5767],
        [0.5598],
        [0.5421],
        [0.5182],
        [0.5762],
        [0.6030],
        [0.4918],
        [0.5403],
        [0.5643],
        [0.5021],
        [0.6062],
        [0.5732],
        [0.6104],
        [0.5573],
        [0.5422],
        [0.5472],
        [0.6142],
        [0.6262],
        [0.5286],
        [0.4643],
        [0.5650],
        [0.5436],
        [0.5534],
        [0.5478],
        [0.5617],
        [0.5730],
        [0.5342],
        [0

In [31]:
model.layer_1.weight

Parameter containing:
tensor([[-0.0651,  0.1786,  0.0734,  0.1008, -0.2322,  0.0068, -0.0244, -0.0925,
          0.2633,  0.2061,  0.0457,  0.1999]], requires_grad=True)

In [32]:
model.layer_1.bias

Parameter containing:
tensor([-0.0886], requires_grad=True)

In [34]:
from torchinfo import summary

summary(model, input_size=(1000,12))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [1000, 1]                 --
├─Linear: 1-1                            [1000, 1]                 13
├─Sigmoid: 1-2                           [1000, 1]                 --
Total params: 13
Trainable params: 13
Non-trainable params: 0
Total mult-adds (M): 0.01
Input size (MB): 0.05
Forward/backward pass size (MB): 0.01
Params size (MB): 0.00
Estimated Total Size (MB): 0.06