In [1]:
import torch
import torch.nn as nn

In [2]:
class Model(nn.Module):
    def __init__(self,num_features):

        super().__init__()
        self.linear1= nn.Linear(num_features,1)
        self.sigmoid= nn.Sigmoid()

    def forward(self,features):
        out=self.linear1(features)
        out=self.sigmoid(out)

        return out

In [3]:
#Crete a datasets
x=torch.rand(10, 5)
#Create a model
# Model(fetures.shape[1])

# #Forward pass
# Model(features)
# fetures.shape[1]


In [4]:
model = Model(x.shape[1])
# Forward pass
model(x)

tensor([[0.4375],
        [0.4925],
        [0.5626],
        [0.4928],
        [0.5497],
        [0.5062],
        [0.4644],
        [0.4686],
        [0.5643],
        [0.5192]], grad_fn=<SigmoidBackward0>)

In [5]:
model.linear1.weight
# model.linear1.weight.shapes

Parameter containing:
tensor([[ 0.3005,  0.0559, -0.0181,  0.1081,  0.4429]], requires_grad=True)

In [6]:
model.linear1.bias

Parameter containing:
tensor([-0.4402], requires_grad=True)

In [7]:
# %pip install torchinfo    

In [8]:
from torchinfo import summary
# Model summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00