In [1]:
import torch
import torch.nn as nn

In [2]:
class Model(nn.Module):
    def __init__(self,input_features):
    
        super().__init__()
        self.hidden= nn.Linear(input_features, 4)
        self.Relu1= nn.ReLU()
        self.hidden2= nn.Linear(4,3)
        self.Relu2= nn.ReLU()
        self.hidden3= nn.Linear(3,2)
        self.Relu3= nn.ReLU()
        self.hidden4= nn.Linear(2,1)
        self.sigmoid= nn.Sigmoid()

    def forward(self, x):
        out = self.hidden(x)
        out = self.Relu1(out)
        out = self.hidden2(out)
        out = self.Relu2(out)
        out = self.hidden3(out)
        out = self.Relu3(out)
        out = self.hidden4(out)
        out = self.sigmoid(out)
        return x

In [3]:
# Create a Dataser for testing

features = torch.rand(100,5)

# Create an instance of the model
model = Model(features.shape[1])



In [4]:
model(features)

tensor([[3.1140e-01, 3.0610e-01, 5.3345e-01, 5.1881e-01, 3.8781e-02],
        [6.7876e-01, 1.6090e-01, 4.5407e-01, 2.4059e-02, 8.8678e-01],
        [8.0920e-01, 8.2910e-01, 6.4556e-01, 8.1980e-01, 7.1353e-01],
        [9.3871e-01, 9.1341e-01, 6.7878e-01, 5.9989e-01, 4.8738e-01],
        [3.2058e-01, 5.9324e-01, 2.1128e-01, 3.7919e-01, 3.3136e-01],
        [6.4724e-01, 9.2353e-01, 5.8609e-01, 5.9348e-01, 7.4404e-01],
        [5.2025e-02, 4.0089e-01, 4.4310e-02, 8.9717e-01, 7.6191e-01],
        [3.4264e-01, 3.6476e-01, 5.4188e-02, 8.6916e-01, 4.7659e-02],
        [6.7725e-01, 8.8655e-01, 9.7697e-01, 3.9630e-01, 2.1484e-01],
        [8.4581e-01, 6.5513e-01, 8.6233e-01, 1.6890e-01, 2.4971e-01],
        [5.1182e-01, 7.4855e-01, 4.0652e-01, 3.4614e-01, 9.6616e-02],
        [3.5104e-01, 6.3754e-02, 2.0627e-01, 3.3843e-01, 6.5601e-01],
        [7.1483e-01, 3.1917e-01, 8.1274e-01, 5.9253e-01, 1.5988e-01],
        [5.2591e-01, 8.6647e-01, 5.8919e-01, 6.4906e-01, 1.9953e-01],
        [6.4556e-01,

In [5]:
model.hidden.weight

Parameter containing:
tensor([[ 0.3028, -0.2079,  0.4024,  0.3866, -0.3497],
        [-0.0292,  0.2835,  0.3494, -0.2279,  0.1736],
        [ 0.1564, -0.1100, -0.2337, -0.2208,  0.2710],
        [-0.3859,  0.2523,  0.0246, -0.3638, -0.0490]], requires_grad=True)

In [6]:
from torchinfo import summary
summary(model, input_size=(100, 5), col_names=["input_size", "output_size", "num_params", "trainable"], col_width=20, row_settings=["var_names"])

Layer (type (var_name))                  Input Shape          Output Shape         Param #              Trainable
Model (Model)                            [100, 5]             [100, 5]             --                   True
├─Linear (hidden)                        [100, 5]             [100, 4]             24                   True
├─ReLU (Relu1)                           [100, 4]             [100, 4]             --                   --
├─Linear (hidden2)                       [100, 4]             [100, 3]             15                   True
├─ReLU (Relu2)                           [100, 3]             [100, 3]             --                   --
├─Linear (hidden3)                       [100, 3]             [100, 2]             8                    True
├─ReLU (Relu3)                           [100, 2]             [100, 2]             --                   --
├─Linear (hidden4)                       [100, 2]             [100, 1]             3                    True
├─Sigmoid (sigmoid) 

In [7]:
#in this layer we use sequential layers


class Model2(nn.Module):
    def __init__(self, input_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_features, 4),
            nn.ReLU(),
            nn.Linear(4, 3),
            nn.ReLU(),
            nn.Linear(3, 2),
            nn.ReLU(),
            nn.Linear(2, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        out = self.network(x)
        return out

In [8]:
# creat Dataset for testing

features2 = torch.rand(50000, 5)

# Create an instance of the model
model2 = Model2(features2.shape[1])
model2(features2)

tensor([[0.3134],
        [0.3166],
        [0.3135],
        ...,
        [0.3134],
        [0.3133],
        [0.3138]], grad_fn=<SigmoidBackward0>)

In [9]:
from torchinfo import summary
summary(model2, input_size=(100, 5), col_names=["input_size", "output_size", "num_params", "trainable"], col_width=20, row_settings=["var_names"])

Layer (type (var_name))                  Input Shape          Output Shape         Param #              Trainable
Model2 (Model2)                          [100, 5]             [100, 1]             --                   True
├─Sequential (network)                   [100, 5]             [100, 1]             --                   True
│    └─Linear (0)                        [100, 5]             [100, 4]             24                   True
│    └─ReLU (1)                          [100, 4]             [100, 4]             --                   --
│    └─Linear (2)                        [100, 4]             [100, 3]             15                   True
│    └─ReLU (3)                          [100, 3]             [100, 3]             --                   --
│    └─Linear (4)                        [100, 3]             [100, 2]             8                    True
│    └─ReLU (5)                          [100, 2]             [100, 2]             --                   --
│    └─Linear (6)   