In [17]:
import torch
import torch.nn as nn

In [24]:
class Model(nn.Module):
    def __init__(self,input_features):
    
        super().__init__()
        self.hidden= nn.Linear(input_features, 4)
        self.Relu1= nn.ReLU()
        self.hidden2= nn.Linear(4,3)
        self.Relu2= nn.ReLU()
        self.hidden3= nn.Linear(3,2)
        self.Relu3= nn.ReLU()
        self.hidden4= nn.Linear(2,1)
        self.sigmoid= nn.Sigmoid()

    def forward(self, x):
        out = self.hidden(x)
        out = self.Relu1(out)
        out = self.hidden2(out)
        out = self.Relu2(out)
        out = self.hidden3(out)
        out = self.Relu3(out)
        out = self.hidden4(out)
        out = self.sigmoid(out)
        return x

In [25]:
# Create a Dataser for testing

features = torch.rand(100,5)

# Create an instance of the model
model = Model(features.shape[1])



In [26]:
model(features)

tensor([[0.4690, 0.3753, 0.9165, 0.6568, 0.7371],
        [0.3338, 0.0499, 0.1126, 0.5953, 0.7324],
        [0.7770, 0.5913, 0.8909, 0.6011, 0.9800],
        [0.1401, 0.3790, 0.0928, 0.8757, 0.9233],
        [0.2705, 0.9373, 0.0336, 0.0658, 0.0260],
        [0.8550, 0.5346, 0.2060, 0.2470, 0.2560],
        [0.8344, 0.7672, 0.0139, 0.9262, 0.2512],
        [0.6600, 0.8206, 0.2981, 0.2927, 0.0029],
        [0.6570, 0.4903, 0.9787, 0.0690, 0.0794],
        [0.1603, 0.8514, 0.4750, 0.2801, 0.5716],
        [0.1498, 0.2099, 0.2264, 0.8910, 0.3785],
        [0.9122, 0.4219, 0.4841, 0.1184, 0.8662],
        [0.9947, 0.5621, 0.3284, 0.3216, 0.6046],
        [0.6445, 0.2696, 0.2124, 0.9782, 0.3602],
        [0.6922, 0.8530, 0.9232, 0.7611, 0.6274],
        [0.1271, 0.4045, 0.4663, 0.7838, 0.8367],
        [0.5437, 0.7997, 0.3128, 0.1999, 0.5982],
        [0.2707, 0.6354, 0.6123, 0.5272, 0.2450],
        [0.5882, 0.2714, 0.6814, 0.5334, 0.7992],
        [0.4396, 0.2450, 0.9494, 0.3827, 0.4760],


In [27]:
model.hidden.weight

Parameter containing:
tensor([[-0.1702,  0.2380, -0.3958, -0.1490,  0.0423],
        [-0.4007,  0.1865,  0.3718, -0.0358, -0.3570],
        [ 0.2174,  0.0898, -0.0224, -0.2324, -0.2516],
        [-0.4451, -0.0442,  0.0674,  0.4017,  0.2245]], requires_grad=True)

In [28]:
from torchinfo import summary
summary(model, input_size=(100, 5), col_names=["input_size", "output_size", "num_params", "trainable"], col_width=20, row_settings=["var_names"])

Layer (type (var_name))                  Input Shape          Output Shape         Param #              Trainable
Model (Model)                            [100, 5]             [100, 5]             --                   True
├─Linear (hidden)                        [100, 5]             [100, 4]             24                   True
├─ReLU (Relu1)                           [100, 4]             [100, 4]             --                   --
├─Linear (hidden2)                       [100, 4]             [100, 3]             15                   True
├─ReLU (Relu2)                           [100, 3]             [100, 3]             --                   --
├─Linear (hidden3)                       [100, 3]             [100, 2]             8                    True
├─ReLU (Relu3)                           [100, 2]             [100, 2]             --                   --
├─Linear (hidden4)                       [100, 2]             [100, 1]             3                    True
├─Sigmoid (sigmoid) 

In [31]:
#in this layer we use sequential layers


class Model2(nn.Module):
    def __init__(self, input_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_features, 4),
            nn.ReLU(),
            nn.Linear(4, 3),
            nn.ReLU(),
            nn.Linear(3, 2),
            nn.ReLU(),
            nn.Linear(2, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        out = self.network(x)
        return out

In [32]:
# creat Dataset for testing

features2 = torch.rand(50000, 5)

# Create an instance of the model
model2 = Model2(features2.shape[1])
model2(features2)

tensor([[0.5110],
        [0.5126],
        [0.5108],
        ...,
        [0.5125],
        [0.5124],
        [0.5107]], grad_fn=<SigmoidBackward0>)

In [34]:
from torchinfo import summary
summary(model2, input_size=(100, 5), col_names=["input_size", "output_size", "num_params", "trainable"], col_width=20, row_settings=["var_names"])

Layer (type (var_name))                  Input Shape          Output Shape         Param #              Trainable
Model2 (Model2)                          [100, 5]             [100, 1]             --                   True
├─Sequential (network)                   [100, 5]             [100, 1]             --                   True
│    └─Linear (0)                        [100, 5]             [100, 4]             24                   True
│    └─ReLU (1)                          [100, 4]             [100, 4]             --                   --
│    └─Linear (2)                        [100, 4]             [100, 3]             15                   True
│    └─ReLU (3)                          [100, 3]             [100, 3]             --                   --
│    └─Linear (4)                        [100, 3]             [100, 2]             8                    True
│    └─ReLU (5)                          [100, 2]             [100, 2]             --                   --
│    └─Linear (6)   