In [1]:
import torch

print(torch.__version__)

import torch.nn as nn

2.5.1+cu118


In [2]:
features = torch.randn(100, 5)
num_features = features.shape[1]


In [3]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network=nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )
    
    def forward(self, x):
        x = self.network(x)
        return x
    

In [4]:
model = Model(num_features)
model(features)

tensor([[0.3520],
        [0.3414],
        [0.3776],
        [0.3325],
        [0.4870],
        [0.3638],
        [0.3870],
        [0.4065],
        [0.3567],
        [0.4417],
        [0.3881],
        [0.4292],
        [0.4615],
        [0.3952],
        [0.4703],
        [0.3988],
        [0.4210],
        [0.4163],
        [0.3585],
        [0.3804],
        [0.4195],
        [0.3599],
        [0.4655],
        [0.3360],
        [0.4665],
        [0.4962],
        [0.4367],
        [0.4730],
        [0.4844],
        [0.4580],
        [0.3908],
        [0.3686],
        [0.3849],
        [0.4016],
        [0.4136],
        [0.3784],
        [0.4072],
        [0.4195],
        [0.4162],
        [0.3985],
        [0.3992],
        [0.4237],
        [0.3183],
        [0.4410],
        [0.3954],
        [0.4274],
        [0.3994],
        [0.5040],
        [0.3694],
        [0.4323],
        [0.3763],
        [0.4862],
        [0.4146],
        [0.4174],
        [0.4131],
        [0

In [5]:
model.network[0].weight

Parameter containing:
tensor([[-0.0728,  0.3307,  0.3670, -0.2710, -0.0201],
        [-0.2362, -0.3563, -0.1161, -0.1238, -0.2363],
        [ 0.1087, -0.0208, -0.3988,  0.2032, -0.1017]], requires_grad=True)

In [6]:
model.network[2].weight

Parameter containing:
tensor([[-0.3100, -0.4103,  0.2698]], requires_grad=True)

In [7]:
from torchinfo import summary
summary(model, input_size=(features.shape[0],features.shape[1]))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [100, 1]                  --
├─Sequential: 1-1                        [100, 1]                  --
│    └─Linear: 2-1                       [100, 3]                  18
│    └─ReLU: 2-2                         [100, 3]                  --
│    └─Linear: 2-3                       [100, 1]                  4
│    └─Sigmoid: 2-4                      [100, 1]                  --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.01