In [10]:
import torch

print(torch.__version__)

import torch.nn as nn

2.5.1+cu118


In [11]:
features = torch.randn(100, 5)
num_features = features.shape[1]


In [12]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network=nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )
    
    def forward(self, x):
        x = self.network(x)
        return x
    

In [13]:
model = Model(num_features)
model(features)

tensor([[0.6397],
        [0.4956],
        [0.5983],
        [0.5834],
        [0.6277],
        [0.5358],
        [0.5020],
        [0.5827],
        [0.5821],
        [0.6045],
        [0.5971],
        [0.5989],
        [0.5475],
        [0.5821],
        [0.5862],
        [0.6247],
        [0.5830],
        [0.6378],
        [0.4523],
        [0.5198],
        [0.6240],
        [0.5805],
        [0.6329],
        [0.5777],
        [0.5650],
        [0.5290],
        [0.5813],
        [0.5302],
        [0.6742],
        [0.5476],
        [0.6177],
        [0.6119],
        [0.5839],
        [0.5622],
        [0.5817],
        [0.4696],
        [0.4269],
        [0.4739],
        [0.5060],
        [0.3759],
        [0.4543],
        [0.4747],
        [0.5826],
        [0.5684],
        [0.5345],
        [0.4599],
        [0.5950],
        [0.5817],
        [0.6120],
        [0.6111],
        [0.5810],
        [0.5572],
        [0.4775],
        [0.5288],
        [0.5911],
        [0

In [16]:
model.network[0].weight

Parameter containing:
tensor([[ 0.4307, -0.1419,  0.0672, -0.1922,  0.3767],
        [-0.3140,  0.2564,  0.3697,  0.3653, -0.1673],
        [-0.2031, -0.0587, -0.3588,  0.0695, -0.3155]], requires_grad=True)

In [18]:
model.network[2].weight

Parameter containing:
tensor([[-0.0174, -0.4071,  0.4605]], requires_grad=True)

In [19]:
from torchinfo import summary
summary(model, input_size=(features.shape[0],features.shape[1]))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [100, 1]                  --
├─Sequential: 1-1                        [100, 1]                  --
│    └─Linear: 2-1                       [100, 3]                  18
│    └─ReLU: 2-2                         [100, 3]                  --
│    └─Linear: 2-3                       [100, 1]                  4
│    └─Sigmoid: 2-4                      [100, 1]                  --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.01