In [15]:
from sklearn.datasets import make_classification
import torch


In [16]:
X,y=make_classification(
    n_samples=1000,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [17]:
X.shape

(1000, 2)

In [18]:
y.shape

(1000,)

In [19]:
y

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,

In [20]:
X

array([[-0.99910178, -0.66386   ],
       [ 1.24668618,  1.15359685],
       [ 0.96277683,  0.85939747],
       ...,
       [-0.10126746, -1.59017563],
       [ 0.64376105, -0.78053855],
       [ 0.69852984, -1.27940455]])

In [21]:
# Covert the data to pytorch tensors

X=torch.tensor(X, dtype=torch.float32)
y=torch.tensor(y,dtype=torch.long)
X

tensor([[-0.9991, -0.6639],
        [ 1.2467,  1.1536],
        [ 0.9628,  0.8594],
        ...,
        [-0.1013, -1.5902],
        [ 0.6438, -0.7805],
        [ 0.6985, -1.2794]])

In [22]:
from torch.utils.data import DataLoader, Dataset


In [23]:
class CustomDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y
    
    def __len__(self):
        return len(self.X)
    
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

In [24]:
datasets=CustomDataset(X,y)

In [25]:
len(datasets)

1000

In [33]:
datasets[0]

(tensor([-0.9991, -0.6639]), tensor(1))

In [42]:
dataloader=DataLoader(datasets,batch_size=10,shuffle=True)

In [43]:
for batch_features,batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("-"*100)
    

tensor([[-0.7265, -0.2006],
        [ 0.6198, -1.3482],
        [ 2.0439, -1.6562],
        [-1.1709, -1.3168],
        [-0.6300, -0.7202],
        [ 1.5732,  1.6144],
        [-0.5700, -0.2725],
        [-2.9368,  2.0884],
        [ 0.1731, -0.9009],
        [ 1.6136,  1.6184]])
tensor([0, 0, 0, 0, 1, 1, 1, 1, 0, 1])
----------------------------------------------------------------------------------------------------
tensor([[-0.0424,  0.2848],
        [-0.0664,  0.4094],
        [-0.8950,  1.6345],
        [-1.1110, -1.6200],
        [ 0.3972,  3.3075],
        [-0.9601, -0.3888],
        [ 0.2444,  0.2314],
        [-0.4460,  0.8178],
        [ 2.2615,  2.2928],
        [ 1.7108,  1.5738]])
tensor([1, 1, 1, 0, 1, 0, 1, 0, 1, 1])
----------------------------------------------------------------------------------------------------
tensor([[ 1.1892,  1.2144],
        [-0.5453,  0.6653],
        [-0.6667,  0.5217],
        [ 2.3297, -0.4450],
        [ 1.5003, -1.4214],
        [ 0.9001, 