In [19]:
from sklearn.datasets import make_classification
import torch


In [20]:
X,y=make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [21]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [22]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [23]:
print(X.shape)
print(y.shape)

(10, 2)
(10,)


In [24]:
# Covert the data to pytorch tensors

X=torch.tensor(X, dtype=torch.float32)
y=torch.tensor(y,dtype=torch.long)

In [25]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [26]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [27]:
from torch.utils.data import Dataset, DataLoader

class CustomDatasetsclass(Dataset):
    def __init__(self, data, labels):
        self.data = data
        self.labels = labels

    def __len__(self):
        return self.data.shape[0]
    
    def __getitem__(self,index):
        return self.data[index], self.labels[index]

    

In [28]:
dataset= CustomDatasetsclass(X,y)

In [29]:
len(dataset)

10

In [30]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [33]:
# dataloader=DataLoader(dataset,batch_size=2,shuffle=True)
dataloader=DataLoader(dataset,batch_size=2,shuffle=False)

In [34]:
for x,y in dataloader:
    print(x)
    print(y)
    print("-"*60)

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1, 0])
------------------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
tensor([0, 0])
------------------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])
------------------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([1, 1])
------------------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1, 0])
------------------------------------------------------------
