In [1]:
# %pip install numpy
# %pip install matplotlib
# %pip install scikit-learn
# %pip install seaborn
# %pip install scikit-learn

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_moons


In [2]:
import  torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
import pandas as pd
df=pd.read_csv('Data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [6]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    object 
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  5

In [8]:
# df.iloc[:,0:1]

### Train Split

In [9]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [10]:
X_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
96        12.180         17.84           77.79      451.1          0.10450   
316       12.180         14.08           77.25      461.4          0.07734   
493       12.460         12.83           78.83      477.3          0.07372   
0         17.990         10.38          122.80     1001.0          0.11840   
157       16.840         19.46          108.40      880.2          0.07445   
..           ...           ...             ...        ...              ...   
199       14.450         20.22           94.49      642.7          0.09872   
152        9.731         15.34           63.78      300.2          0.10720   
262       17.290         22.13          114.40      947.8          0.08999   
197       18.080         21.84          117.40     1024.0          0.07371   
259       15.530         33.56          103.70      744.9          0.10630   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
96            0.07057        0.024900             0.029410         0.1900   
316           0.03212        0.011230             0.005051         0.1673   
493           0.04043        0.007173             0.011490         0.1613   
0             0.27760        0.300100             0.147100         0.2419   
157           0.07223        0.051500             0.027710         0.1844   
..                ...             ...                  ...            ...   
199           0.12060        0.118000             0.059800         0.1950   
152           0.15990        0.410800             0.078570         0.2548   
262           0.12730        0.096970             0.075070         0.2108   
197           0.08642        0.110300             0.057780         0.1770   
259           0.16390        0.175100             0.083990         0.2091   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
96                  0.06635  ...         12.83          20.92   
316                 0.05649  ...         12.85          16.47   
493                 0.06013  ...         13.19          16.36   
0                   0.07871  ...         25.38          17.33   
157                 0.05268  ...         18.22          28.07   
..                      ...  ...           ...            ...   
199                 0.06466  ...         18.33          30.12   
152                 0.09296  ...         11.02          19.49   
262                 0.05464  ...         20.39          27.24   
197                 0.05340  ...         19.76          24.70   
259                 0.06650  ...         18.49          49.54   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
96             82.14       495.2           0.11400            0.09358   
316            81.60       513.1           0.10010            0.05332   
493            83.24       534.0           0.09439            0.06477   
0             184.60      2019.0           0.16220            0.66560   
157           120.30      1032.0           0.08774            0.17100   
..               ...         ...               ...                ...   
199           117.90      1044.0           0.15520            0.40560   
152            71.04       380.5           0.12920            0.27720   
262           137.90      1295.0           0.11340            0.28670   
197           129.10      1228.0           0.08822            0.19630   
259           126.30      1035.0           0.18830            0.55640   

     concavity_worst  concave points_worst  symmetry_worst  \
96           0.04980               0.05882          0.2227   
316          0.04116               0.01852          0.2293   
493          0.01674               0.02680          0.2280   
0            0.71190               0.26540          0.4601   
157          0.18820               0.08436          0.2527   
..               ...                   ...             ...   
199          0.49670               0.18380         

### Scaling

In [11]:
scaler= StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
X_train

array([[-0.5554964 , -0.34357554, -0.58708373, ..., -0.84909226,
        -1.08856375, -0.56576889],
       [-0.5554964 , -1.22418474, -0.60975187, ..., -1.46815924,
        -0.98109661, -1.34014679],
       [-0.47423564, -1.51694045, -0.54342656, ..., -1.34096632,
        -1.00226438, -0.76702618],
       ...,
       [ 0.92751251,  0.66116209,  0.94973252, ...,  0.59457807,
         0.27919984, -0.50330973],
       [ 1.15678394,  0.59324276,  1.07566666, ..., -0.34231758,
        -0.85734657, -1.03883918],
       [ 0.41673057,  3.33812037,  0.50056743, ...,  1.34114519,
         1.00378889,  2.13154144]])

### Lable Encoding

In [13]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [14]:
y_train.shape

(455,)

In [15]:
X_train.shape[1]

30

## Numpy Array to pytorch Tensors

In [16]:
X_train_tensor = torch.tensor(X_train)
X_test_tensor = torch.tensor(X_test)
y_train_tensor = torch.tensor(y_train)
y_test_tensor = torch.tensor(y_test)

In [17]:
X_train_tensor.shape

torch.Size([455, 30])

In [18]:
X_train_tensor.shape[1]

30

In [19]:
X_train.shape[1],1

(30, 1)

In [20]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [21]:
# Make a class for the model
import torch.nn as nn
import torch.nn.functional as F
class MysimpaleNN():
    def __init__(self,X):
        self.weights=torch.rand(X.shape[1],1,requires_grad=True,dtype=torch.float64)
        self.bias=torch.zeros(1,requires_grad=True,dtype=torch.float64)

    def forward(self,X):
        z=torch.matmul(X,self.weights)+self.bias
        y_pred=torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss
        # loss =torch.nn.BCELoss()
        # return  loss(y_pred, y)


### Important Parameters

In [22]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [23]:
#create an instance of the model
model=MysimpaleNN(X_train_tensor)

# Define loop for training

for i in range(epochs):
    #Foraward pass
    y_pred=model.forward(X_train_tensor)
    # print(y_pred.shape)
    torch.Size([455, 1])
    #Calculate the loss
    loss=model.loss_function(y_pred,y_train_tensor)
    # print(loss)
    # print(loss.shape)

    # Backward pass
    loss.backward()
    # Update parameters
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad   
    # Zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    # Print loss every epoch
    print(f'Epoch {i+1}/{epochs}, Loss: {loss.item()}')

Epoch 1/25, Loss: 3.2962833096430564
Epoch 2/25, Loss: 3.1776599032471777
Epoch 3/25, Loss: 3.0510677124281536
Epoch 4/25, Loss: 2.9172659797035236
Epoch 5/25, Loss: 2.7760901197101435
Epoch 6/25, Loss: 2.6321117765597597
Epoch 7/25, Loss: 2.4856745672345695
Epoch 8/25, Loss: 2.337093956470368
Epoch 9/25, Loss: 2.191542179324438
Epoch 10/25, Loss: 2.05046179892266
Epoch 11/25, Loss: 1.91219929112204
Epoch 12/25, Loss: 1.777259962982478
Epoch 13/25, Loss: 1.6474170926724216
Epoch 14/25, Loss: 1.5235143208507254
Epoch 15/25, Loss: 1.40774650671269
Epoch 16/25, Loss: 1.3033664068222075
Epoch 17/25, Loss: 1.2135277257220083
Epoch 18/25, Loss: 1.1382297665426726
Epoch 19/25, Loss: 1.0765790960015373
Epoch 20/25, Loss: 1.0269112524039912
Epoch 21/25, Loss: 0.9871379104393043
Epoch 22/25, Loss: 0.9551085451622664
Epoch 23/25, Loss: 0.9288802941564082
Epoch 24/25, Loss: 0.9068753196265515
Epoch 25/25, Loss: 0.8879205667716129


In [24]:
model.weights[2]

tensor([0.3554], dtype=torch.float64, grad_fn=<SelectBackward0>)

In [25]:
model.bias

tensor([-0.1504], dtype=torch.float64, requires_grad=True)

### Evaluation

In [26]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5846414566040039
