In [1]:
# %pip install numpy
# %pip install matplotlib
# %pip install scikit-learn
# %pip install seaborn
# %pip install scikit-learn

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_moons


In [2]:
import  torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
import pandas as pd
df=pd.read_csv('Data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [6]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    object 
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  5

In [8]:
# df.iloc[:,0:1]

### Train Split

In [9]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [10]:
X_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
27         18.61         20.25          122.10     1094.0          0.09440   
396        13.51         18.89           88.10      558.1          0.10590   
476        14.20         20.53           92.41      618.4          0.08931   
532        13.68         16.33           87.76      575.5          0.09277   
299        10.51         23.09           66.85      334.2          0.10150   
..           ...           ...             ...        ...              ...   
407        12.85         21.37           82.63      514.5          0.07551   
5          12.45         15.70           82.57      477.1          0.12780   
190        14.22         23.12           94.37      609.9          0.10750   
60         10.17         14.88           64.55      311.9          0.11340   
311        14.61         15.69           92.68      664.9          0.07618   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
27            0.10660         0.14900              0.07731         0.1697   
396           0.11470         0.08580              0.05381         0.1806   
476           0.11080         0.05063              0.03058         0.1506   
532           0.07255         0.01752              0.01880         0.1631   
299           0.06797         0.02495              0.01875         0.1695   
..                ...             ...                  ...            ...   
407           0.08316         0.06126              0.01867         0.1580   
5             0.17000         0.15780              0.08089         0.2087   
190           0.24130         0.19810              0.06618         0.2384   
60            0.08061         0.01084              0.01290         0.2743   
311           0.03515         0.01447              0.01877         0.1632   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
27                  0.05699  ...         21.31          27.26   
396                 0.06079  ...         14.80          27.20   
476                 0.06009  ...         16.45          27.26   
532                 0.06155  ...         15.85          20.20   
299                 0.06556  ...         10.93          24.22   
..                      ...  ...           ...            ...   
407                 0.06114  ...         14.40          27.01   
5                   0.07613  ...         15.47          23.75   
190                 0.07542  ...         15.74          37.18   
60                  0.06960  ...         11.02          17.45   
311                 0.05255  ...         16.46          21.75   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
27            139.90      1403.0           0.13380            0.21170   
396            97.33       675.2           0.14280            0.25700   
476           112.10       828.5           0.11530            0.34290   
532           101.60       773.4           0.12640            0.15640   
299            70.10       362.7           0.11430            0.08614   
..               ...         ...               ...                ...   
407            91.63       645.8           0.09402            0.19360   
5             103.40       741.6           0.17910            0.52490   
190           106.40       762.4           0.15330            0.93270   
60             69.86       368.6           0.12750            0.09866   
311           103.70       840.8           0.10110            0.07087   

     concavity_worst  concave points_worst  symmetry_worst  \
27           0.34460               0.14900          0.2341   
396          0.34380               0.14530          0.2666   
476          0.25120               0.13390          0.2534   
532          0.12060               0.08704          0.2806   
299          0.04158               0.03125          0.2227   
..               ...                   ...             ...   
407          0.18380               0.05601         

### Scaling

In [11]:
scaler= StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
X_train

array([[ 1.31634183,  0.21986921,  1.27978532, ...,  0.53221509,
        -0.93018446, -0.53494457],
       [-0.17419751, -0.08710039, -0.15858941, ...,  0.47542655,
        -0.38970679, -0.38794326],
       [ 0.02746369,  0.28306883,  0.02374574, ...,  0.30045642,
        -0.60922387, -0.29253109],
       ...,
       [ 0.03330895,  0.86766534,  0.10666381, ...,  0.96503593,
         3.76781375,  3.3697431 ],
       [-1.15035465, -0.99220928, -1.15487544, ..., -1.35884358,
         1.09203353, -0.20266613],
       [ 0.14729137, -0.8093818 ,  0.03516812, ..., -0.86248097,
        -0.6158759 , -1.49239462]])

### Lable Encoding

In [13]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [14]:
y_train.shape

(455,)

In [15]:
X_train.shape[1]

30

## Numpy Array to pytorch Tensors

In [16]:
X_train_tensor = torch.tensor(X_train)
X_test_tensor = torch.tensor(X_test)
y_train_tensor = torch.tensor(y_train)
y_test_tensor = torch.tensor(y_test)

In [17]:
X_train_tensor.shape

torch.Size([455, 30])

In [18]:
X_train_tensor.shape[1]

30

In [19]:
X_train.shape[1],1

(30, 1)

In [20]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [21]:
# Make a class for the model
import torch.nn as nn
import torch.nn.functional as F
class MysimpaleNN():
    def __init__(self,X):
        self.weights=torch.rand(X.shape[1],1,requires_grad=True,dtype=torch.float64)
        self.bias=torch.zeros(1,requires_grad=True,dtype=torch.float64)

    def forward(self,X):
        z=torch.matmul(X,self.weights)+self.bias
        y_pred=torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss
        # loss =torch.nn.BCELoss()
        # return  loss(y_pred, y)


### Important Parameters

In [22]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [23]:
#create an instance of the model
model=MysimpaleNN(X_train_tensor)

# Define loop for training

for i in range(epochs):
    #Foraward pass
    y_pred=model.forward(X_train_tensor)
    # print(y_pred.shape)
    torch.Size([455, 1])
    #Calculate the loss
    loss=model.loss_function(y_pred,y_train_tensor)
    # print(loss)
    # print(loss.shape)

    # Backward pass
    loss.backward()
    # Update parameters
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad   
    # Zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    # Print loss every epoch
    print(f'Epoch {i+1}/{epochs}, Loss: {loss.item()}')

Epoch 1/25, Loss: 3.4829452083231334
Epoch 2/25, Loss: 3.361365518398664
Epoch 3/25, Loss: 3.231842492429605
Epoch 4/25, Loss: 3.098900301625218
Epoch 5/25, Loss: 2.964230982217294
Epoch 6/25, Loss: 2.8215273526189333
Epoch 7/25, Loss: 2.6693864610513582
Epoch 8/25, Loss: 2.5085463886396466
Epoch 9/25, Loss: 2.346086694755362
Epoch 10/25, Loss: 2.188714521174807
Epoch 11/25, Loss: 2.033069923378722
Epoch 12/25, Loss: 1.882962575176426
Epoch 13/25, Loss: 1.7374350750381293
Epoch 14/25, Loss: 1.601703202602253
Epoch 15/25, Loss: 1.474052506382677
Epoch 16/25, Loss: 1.3560880811378118
Epoch 17/25, Loss: 1.2456482579898183
Epoch 18/25, Loss: 1.1513800255555264
Epoch 19/25, Loss: 1.0731571594908906
Epoch 20/25, Loss: 1.0101378809230719
Epoch 21/25, Loss: 0.9607491650835615
Epoch 22/25, Loss: 0.9227963721769766
Epoch 23/25, Loss: 0.8937874103651652
Epoch 24/25, Loss: 0.8713566908727933
Epoch 25/25, Loss: 0.8535622509092626


In [24]:
model.weights[2]

tensor([0.2776], dtype=torch.float64, grad_fn=<SelectBackward0>)

In [25]:
model.bias

tensor([-0.0956], dtype=torch.float64, requires_grad=True)

### Evaluation

In [26]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6200369596481323
