In [1]:
# %pip install numpy
# %pip install matplotlib
# %pip install scikit-learn
# %pip install seaborn
# %pip install scikit-learn

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_moons


In [2]:
import  torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
import pandas as pd
df=pd.read_csv('Data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [6]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    object 
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  5

In [8]:
# df.iloc[:,0:1]

### Train Split

In [9]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [10]:
X_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
360       12.540         18.07           79.42      491.9          0.07436   
167       16.780         18.80          109.30      886.3          0.08865   
43        13.280         20.28           87.32      545.2          0.10410   
490       12.250         22.44           78.18      466.5          0.08192   
517       19.890         20.26          130.50     1214.0          0.10370   
..           ...           ...             ...        ...              ...   
226       10.440         15.46           66.62      329.6          0.10530   
92        13.270         14.76           84.74      551.7          0.07355   
176        9.904         18.06           64.60      302.4          0.09699   
337       18.770         21.43          122.90     1092.0          0.09116   
291       14.960         19.10           97.03      687.3          0.08992   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
360           0.02650        0.001194             0.005449         0.1528   
167           0.09182        0.084220             0.065760         0.1893   
43            0.14360        0.098470             0.061580         0.1974   
490           0.05200        0.017140             0.012610         0.1544   
517           0.13100        0.141100             0.094310         0.1802   
..                ...             ...                  ...            ...   
226           0.07722        0.006643             0.012160         0.1788   
92            0.05055        0.032610             0.026480         0.1386   
176           0.12940        0.130700             0.037160         0.1669   
337           0.14020        0.106000             0.060900         0.1953   
291           0.09823        0.059400             0.048190         0.1879   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
360                 0.05185  ...         13.72          20.98   
167                 0.05534  ...         20.05          26.30   
43                  0.06782  ...         17.38          28.00   
490                 0.05976  ...         14.17          31.99   
517                 0.06188  ...         23.73          25.23   
..                      ...  ...           ...            ...   
226                 0.06450  ...         11.52          19.80   
92                  0.05318  ...         16.36          22.35   
176                 0.08116  ...         11.26          24.39   
337                 0.06083  ...         24.54          34.37   
291                 0.05852  ...         16.25          26.19   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
360            86.82       585.7           0.09293            0.04327   
167           130.70      1260.0           0.11680            0.21190   
43            113.10       907.2           0.15300            0.37240   
490            92.74       622.9           0.12560            0.18040   
517           160.50      1646.0           0.14170            0.33090   
..               ...         ...               ...                ...   
226            73.47       395.4           0.13410            0.11530   
92            104.50       830.6           0.10060            0.12380   
176            73.07       390.2           0.13010            0.29500   
337           161.10      1873.0           0.14980            0.48270   
291           109.10       809.8           0.13130            0.30300   

     concavity_worst  concave points_worst  symmetry_worst  \
360         0.003581               0.01635          0.2233   
167         0.231800               0.14740          0.2810   
43          0.366400               0.14920          0.3739   
490         0.123000               0.06335          0.3100   
517         0.418500               0.16130          0.2549   
..               ...                   ...             ...   
226         0.026390               0.04464         

### Scaling

In [11]:
scaler= StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
X_train

array([[-0.41762408, -0.27647261, -0.48270925, ..., -1.46598843,
        -1.07693237, -1.62404482],
       [ 0.78277339, -0.11081846,  0.74668653, ...,  0.52876745,
        -0.13215415, -0.63855926],
       [-0.20812075,  0.2250283 , -0.15766819, ...,  0.55616585,
         1.3889879 ,  1.11764874],
       ...,
       [-1.16390892, -0.27874184, -1.0924698 , ..., -0.20642301,
        -0.45308401,  1.89703099],
       [ 1.34616748,  0.48599031,  1.30625087, ...,  1.40247205,
         1.29074406,  0.88672066],
       [ 0.26750844, -0.04274141,  0.24184429, ...,  0.55159945,
         0.11673023,  0.07962705]])

### Lable Encoding

In [13]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [14]:
y_train.shape

(455,)

In [15]:
X_train.shape[1]

30

## Numpy Array to pytorch Tensors

In [16]:
X_train_tensor = torch.tensor(X_train)
X_test_tensor = torch.tensor(X_test)
y_train_tensor = torch.tensor(y_train)
y_test_tensor = torch.tensor(y_test)

In [17]:
X_train_tensor.shape

torch.Size([455, 30])

In [18]:
X_train_tensor.shape[1]

30

In [19]:
X_train.shape[1],1

(30, 1)

In [20]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [21]:
# Make a class for the model
import torch.nn as nn
import torch.nn.functional as F
class MysimpaleNN():
    def __init__(self,X):
        self.weights=torch.rand(X.shape[1],1,requires_grad=True,dtype=torch.float64)
        self.bias=torch.zeros(1,requires_grad=True,dtype=torch.float64)

    def forward(self,X):
        z=torch.matmul(X,self.weights)+self.bias
        y_pred=torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss
        # loss =torch.nn.BCELoss()
        # return  loss(y_pred, y)


### Important Parameters

In [22]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [23]:
#create an instance of the model
model=MysimpaleNN(X_train_tensor)

# Define loop for training

for i in range(epochs):
    #Foraward pass
    y_pred=model.forward(X_train_tensor)
    # print(y_pred.shape)
    torch.Size([455, 1])
    #Calculate the loss
    loss=model.loss_function(y_pred,y_train_tensor)
    # print(loss)
    # print(loss.shape)

    # Backward pass
    loss.backward()
    # Update parameters
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad   
    # Zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    # Print loss every epoch
    print(f'Epoch {i+1}/{epochs}, Loss: {loss.item()}')

Epoch 1/25, Loss: 3.823787500461156
Epoch 2/25, Loss: 3.719596465813713
Epoch 3/25, Loss: 3.6133753583962536
Epoch 4/25, Loss: 3.50417592836201
Epoch 5/25, Loss: 3.3914039354270575
Epoch 6/25, Loss: 3.275706155794693
Epoch 7/25, Loss: 3.1518555314656815
Epoch 8/25, Loss: 3.0199513013360204
Epoch 9/25, Loss: 2.8812448916781532
Epoch 10/25, Loss: 2.7387127210787217
Epoch 11/25, Loss: 2.5898272073407216
Epoch 12/25, Loss: 2.434251447843375
Epoch 13/25, Loss: 2.2763087015762693
Epoch 14/25, Loss: 2.111055756859957
Epoch 15/25, Loss: 1.9466275104269788
Epoch 16/25, Loss: 1.788404284179519
Epoch 17/25, Loss: 1.6310164791160444
Epoch 18/25, Loss: 1.4843390948195507
Epoch 19/25, Loss: 1.3499814425655532
Epoch 20/25, Loss: 1.2287556255701029
Epoch 21/25, Loss: 1.1199400792961265
Epoch 22/25, Loss: 1.0278644638061498
Epoch 23/25, Loss: 0.9530077542637412
Epoch 24/25, Loss: 0.8949106636401802
Epoch 25/25, Loss: 0.851950856415981


In [24]:
model.weights[2]

tensor([-0.0410], dtype=torch.float64, grad_fn=<SelectBackward0>)

In [25]:
model.bias

tensor([-0.0924], dtype=torch.float64, requires_grad=True)

### Evaluation

In [26]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5769467353820801
