In [134]:
# %pip install numpy
# %pip install matplotlib
# %pip install scikit-learn
# %pip install seaborn
# %pip install scikit-learn

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_moons


In [135]:
import  torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [136]:
import pandas as pd
df=pd.read_csv('Data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [137]:
df.shape

(569, 33)

In [138]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [139]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    object 
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  5

In [141]:
# df.iloc[:,0:1]

### Train Split

In [142]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [143]:
X_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
81         13.34         15.86           86.49      520.0          0.10780   
123        14.50         10.89           94.28      640.7          0.11010   
452        12.00         28.23           76.77      442.5          0.08437   
191        12.77         21.41           82.02      507.4          0.08749   
265        20.73         31.12          135.70     1419.0          0.09469   
..           ...           ...             ...        ...              ...   
57         14.71         21.59           95.55      656.9          0.11370   
245        10.48         19.86           66.72      337.7          0.10700   
102        12.18         20.52           77.22      458.7          0.08013   
455        13.38         30.72           86.34      557.2          0.09245   
79         12.86         18.00           83.19      506.3          0.09934   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
81            0.15350         0.11690              0.06987         0.1942   
123           0.10990         0.08842              0.05778         0.1856   
452           0.06450         0.04055              0.01945         0.1615   
191           0.06601         0.03112              0.02864         0.1694   
265           0.11430         0.13670              0.08646         0.1769   
..                ...             ...                  ...            ...   
57            0.13650         0.12930              0.08123         0.2027   
245           0.05971         0.04831              0.03070         0.1737   
102           0.04038         0.02383              0.01770         0.1739   
455           0.07426         0.02819              0.03264         0.1375   
79            0.09546         0.03889              0.02315         0.1718   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
81                  0.06902  ...         15.53          23.19   
123                 0.06402  ...         15.70          15.98   
452                 0.06104  ...         13.09          37.88   
191                 0.06287  ...         13.75          23.50   
265                 0.05674  ...         32.49          47.16   
..                      ...  ...           ...            ...   
57                  0.06758  ...         17.87          30.70   
245                 0.06440  ...         11.48          29.46   
102                 0.05677  ...         13.34          32.84   
455                 0.06016  ...         15.05          41.61   
79                  0.05997  ...         14.24          24.82   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
81             96.66       614.9           0.15360            0.47910   
123           102.80       745.5           0.13130            0.17880   
452            85.07       523.7           0.12080            0.18560   
191            89.04       579.5           0.09388            0.08978   
265           214.00      3432.0           0.14010            0.26440   
..               ...         ...               ...                ...   
57            115.70       985.5           0.13680            0.42900   
245            73.68       402.8           0.15150            0.10260   
102            84.58       547.8           0.11230            0.08862   
455            96.69       705.6           0.11720            0.14210   
79             91.88       622.1           0.12890            0.21410   

     concavity_worst  concave points_worst  symmetry_worst  \
81           0.48580               0.17080          0.3527   
123          0.25600               0.12210          0.2889   
452          0.18110               0.07116          0.2447   
191          0.05186               0.04773          0.2179   
265          0.34420               0.16590          0.2868   
..               ...                   ...             ...   
57           0.35870               0.18340         

### Scaling

In [144]:
scaler= StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [145]:
X_train

array([[-0.24851091, -0.80766034, -0.25248233, ...,  0.7845034 ,
         0.97614121,  0.92543922],
       [ 0.0793812 , -1.93956911,  0.06714586, ...,  0.05407418,
        -0.05118773, -0.24792946],
       [-0.62728284,  2.00958542, -0.65129954, ..., -0.70995179,
        -0.76291091, -0.14551845],
       ...,
       [-0.57640303,  0.25364647, -0.63283578, ..., -0.66270637,
        -0.36518325, -0.86239551],
       [-0.23720429,  2.57667855, -0.25863692, ..., -0.61291119,
        -1.16707951, -0.4282382 ],
       [-0.38419041, -0.3202791 , -0.38788324, ..., -0.58846356,
        -0.22831341, -0.29586653]])

### Lable Encoding

In [146]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [147]:
y_train.shape

(455,)

In [148]:
X_train.shape[1]

30

## Numpy Array to pytorch Tensors

In [149]:
X_train_tensor = torch.tensor(X_train)
X_test_tensor = torch.tensor(X_test)
y_train_tensor = torch.tensor(y_train)
y_test_tensor = torch.tensor(y_test)

In [150]:
X_train_tensor.shape

torch.Size([455, 30])

In [151]:
X_train_tensor.shape[1]

30

In [152]:
X_train.shape[1],1

(30, 1)

In [153]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [154]:
# Make a class for the model
import torch.nn as nn
import torch.nn.functional as F
class MysimpaleNN():
    def __init__(self,X):
        self.weights=torch.rand(X.shape[1],1,requires_grad=True,dtype=torch.float64)
        self.bias=torch.zeros(1,requires_grad=True,dtype=torch.float64)

    def forward(self,X):
        z=torch.matmul(X,self.weights)+self.bias
        y_pred=torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss
        # loss =torch.nn.BCELoss()
        # return  loss(y_pred, y)


### Important Parameters

In [167]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [168]:
#create an instance of the model
model=MysimpaleNN(X_train_tensor)

# Define loop for training

for i in range(epochs):
    #Foraward pass
    y_pred=model.forward(X_train_tensor)
    # print(y_pred.shape)
    torch.Size([455, 1])
    #Calculate the loss
    loss=model.loss_function(y_pred,y_train_tensor)
    # print(loss)
    # print(loss.shape)

    # Backward pass
    loss.backward()
    # Update parameters
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad   
    # Zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    # Print loss every epoch
    print(f'Epoch {i+1}/{epochs}, Loss: {loss.item()}')

Epoch 1/25, Loss: 3.976174206782445
Epoch 2/25, Loss: 3.843113107325873
Epoch 3/25, Loss: 3.7065754597372083
Epoch 4/25, Loss: 3.5645562662060213
Epoch 5/25, Loss: 3.418876234109051
Epoch 6/25, Loss: 3.2715064728971788
Epoch 7/25, Loss: 3.1193238732635122
Epoch 8/25, Loss: 2.9633097662130226
Epoch 9/25, Loss: 2.803793885670575
Epoch 10/25, Loss: 2.6362155413487747
Epoch 11/25, Loss: 2.46345751881084
Epoch 12/25, Loss: 2.29170024453385
Epoch 13/25, Loss: 2.1193385512114644
Epoch 14/25, Loss: 1.9490019778654457
Epoch 15/25, Loss: 1.787507939263062
Epoch 16/25, Loss: 1.6341258860351768
Epoch 17/25, Loss: 1.4870275270681166
Epoch 18/25, Loss: 1.3542738228319684
Epoch 19/25, Loss: 1.237304475384317
Epoch 20/25, Loss: 1.1370480270365644
Epoch 21/25, Loss: 1.0537039916971063
Epoch 22/25, Loss: 0.9865840197794374
Epoch 23/25, Loss: 0.9340708923331851
Epoch 24/25, Loss: 0.8938038451932989
Epoch 25/25, Loss: 0.8631180090885867


In [169]:
model.weights[2]

tensor([0.1148], dtype=torch.float64, grad_fn=<SelectBackward0>)

In [170]:
model.bias

tensor([-0.1012], dtype=torch.float64, requires_grad=True)

### Evaluation

In [171]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6920590996742249
